<?php

// Static reference data for sample Citizen Portal accounts used to demo
// "log in as this resident" — same category as config/esperanza_rbac.php's
// admin accounts, but for citizens. One sample resident per barangay, so the
// barangay picker on the citizen login screen has someone to sign in as for
// every barangay in config/esperanza.php.

return [
    'accounts' => [
        [
            'id' => 'ESP-RES-2024-1102',
            'firstName' => 'Ronaldo',
            'lastName' => 'Bautista',
            'fullName' => 'Ronaldo Panganiban Bautista',
            'email' => 'ronaldo.bautista@email.com',
            'mobile' => '0918 224 5567',
            'barangay' => 'Labangtaytay',
            'purok' => 'Purok 2',
            'address' => 'Purok 2, Barangay Labangtaytay, Esperanza, Masbate',
            'birthdate' => 'August 22, 1990',
            'sex' => 'Male',
            'civilStatus' => 'Married',
            'occupation' => 'Fisherman',
            'residentSince' => 2015,
            'profileCompleteness' => 78,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1203',
            'firstName' => 'Marites',
            'lastName' => 'Ferrer',
            'fullName' => 'Marites Gonzales Ferrer',
            'email' => 'marites.ferrer@email.com',
            'mobile' => '0917 335 8821',
            'barangay' => 'Agoho',
            'purok' => 'Purok 1',
            'address' => 'Purok 1, Barangay Agoho, Esperanza, Masbate',
            'birthdate' => 'March 4, 1985',
            'sex' => 'Female',
            'civilStatus' => 'Married',
            'occupation' => 'Farmer',
            'residentSince' => 2010,
            'profileCompleteness' => 82,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1187',
            'firstName' => 'Joel',
            'lastName' => 'Aranas',
            'fullName' => 'Joel Villanueva Aranas',
            'email' => 'joel.aranas@email.com',
            'mobile' => '0928 441 2093',
            'barangay' => 'Almero',
            'purok' => 'Purok 3',
            'address' => 'Purok 3, Barangay Almero, Esperanza, Masbate',
            'birthdate' => 'June 17, 1992',
            'sex' => 'Male',
            'civilStatus' => 'Single',
            'occupation' => 'Tricycle Driver',
            'residentSince' => 2018,
            'profileCompleteness' => 65,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1044',
            'firstName' => 'Cristy',
            'lastName' => 'Bonghanoy',
            'fullName' => 'Cristy Pareja Bonghanoy',
            'email' => 'cristy.bonghanoy@email.com',
            'mobile' => '0919 502 7734',
            'barangay' => 'Baras',
            'purok' => 'Purok 2',
            'address' => 'Purok 2, Barangay Baras, Esperanza, Masbate',
            'birthdate' => 'November 29, 1988',
            'sex' => 'Female',
            'civilStatus' => 'Married',
            'occupation' => 'Market Vendor',
            'residentSince' => 2012,
            'profileCompleteness' => 90,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1298',
            'firstName' => 'Ariel',
            'lastName' => 'Cabahug',
            'fullName' => 'Ariel Santos Cabahug',
            'email' => 'ariel.cabahug@email.com',
            'mobile' => '0906 213 4457',
            'barangay' => 'Domorog',
            'purok' => 'Purok 4',
            'address' => 'Purok 4, Barangay Domorog, Esperanza, Masbate',
            'birthdate' => 'February 9, 1983',
            'sex' => 'Male',
            'civilStatus' => 'Married',
            'occupation' => 'Seafarer',
            'residentSince' => 2008,
            'profileCompleteness' => 71,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1056',
            'firstName' => 'Lorna',
            'lastName' => 'Dimaano',
            'fullName' => 'Lorna Reyes Dimaano',
            'email' => 'lorna.dimaano@email.com',
            'mobile' => '0917 809 1265',
            'barangay' => 'Guadalupe',
            'purok' => 'Purok 1',
            'address' => 'Purok 1, Barangay Guadalupe, Esperanza, Masbate',
            'birthdate' => 'July 21, 1979',
            'sex' => 'Female',
            'civilStatus' => 'Widowed',
            'occupation' => 'Sari-Sari Store Owner',
            'residentSince' => 2001,
            'profileCompleteness' => 88,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1332',
            'firstName' => 'Bayani',
            'lastName' => 'Espinosa',
            'fullName' => 'Bayani Cruz Espinosa',
            'email' => 'bayani.espinosa@email.com',
            'mobile' => '0928 674 3312',
            'barangay' => 'Iligan',
            'purok' => 'Purok 2',
            'address' => 'Purok 2, Barangay Iligan, Esperanza, Masbate',
            'birthdate' => 'April 30, 1995',
            'sex' => 'Male',
            'civilStatus' => 'Single',
            'occupation' => 'Farmer',
            'residentSince' => 2019,
            'profileCompleteness' => 60,
            'status' => 'Pending Review',
        ],
        [
            'id' => 'ESP-RES-2024-1071',
            'firstName' => 'Divina',
            'lastName' => 'Galvez',
            'fullName' => 'Divina Torres Galvez',
            'email' => 'divina.galvez@email.com',
            'mobile' => '0918 992 5501',
            'barangay' => 'Labrador',
            'purok' => 'Purok 3',
            'address' => 'Purok 3, Barangay Labrador, Esperanza, Masbate',
            'birthdate' => 'October 12, 1986',
            'sex' => 'Female',
            'civilStatus' => 'Married',
            'occupation' => 'Public School Teacher',
            'residentSince' => 2011,
            'profileCompleteness' => 95,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1219',
            'firstName' => 'Ferdinand',
            'lastName' => 'Hilario',
            'fullName' => 'Ferdinand Ramos Hilario',
            'email' => 'ferdinand.hilario@email.com',
            'mobile' => '0906 337 8890',
            'barangay' => 'Libertad',
            'purok' => 'Purok 1',
            'address' => 'Purok 1, Barangay Libertad, Esperanza, Masbate',
            'birthdate' => 'January 25, 1980',
            'sex' => 'Male',
            'civilStatus' => 'Married',
            'occupation' => 'Carpenter',
            'residentSince' => 2005,
            'profileCompleteness' => 74,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1145',
            'firstName' => 'Analiza',
            'lastName' => 'Ibarra',
            'fullName' => 'Analiza Bautista Ibarra',
            'email' => 'analiza.ibarra@email.com',
            'mobile' => '0917 664 2278',
            'barangay' => 'Magsaysay',
            'purok' => 'Purok 5',
            'address' => 'Purok 5, Barangay Magsaysay, Esperanza, Masbate',
            'birthdate' => 'May 3, 1991',
            'sex' => 'Female',
            'civilStatus' => 'Married',
            'occupation' => 'OFW (on home leave)',
            'residentSince' => 2016,
            'profileCompleteness' => 68,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1278',
            'firstName' => 'Romulo',
            'lastName' => 'Jacinto',
            'fullName' => 'Romulo Flores Jacinto',
            'email' => 'romulo.jacinto@email.com',
            'mobile' => '0928 118 6634',
            'barangay' => 'Masbaranon',
            'purok' => 'Purok 2',
            'address' => 'Purok 2, Barangay Masbaranon, Esperanza, Masbate',
            'birthdate' => 'September 14, 1987',
            'sex' => 'Male',
            'civilStatus' => 'Married',
            'occupation' => 'Fisherman',
            'residentSince' => 2013,
            'profileCompleteness' => 80,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1010',
            'firstName' => 'Grace',
            'lastName' => 'Kalaw',
            'fullName' => 'Grace Mendoza Kalaw',
            'email' => 'grace.kalaw@email.com',
            'mobile' => '0919 220 4471',
            'barangay' => 'Poblacion',
            'purok' => 'Purok 6',
            'address' => 'Purok 6, Barangay Poblacion, Esperanza, Masbate',
            'birthdate' => 'December 2, 1989',
            'sex' => 'Female',
            'civilStatus' => 'Single',
            'occupation' => 'Municipal Utility Worker',
            'residentSince' => 2014,
            'profileCompleteness' => 92,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1256',
            'firstName' => 'Danilo',
            'lastName' => 'Lazaro',
            'fullName' => 'Danilo Aquino Lazaro',
            'email' => 'danilo.lazaro@email.com',
            'mobile' => '0906 550 7712',
            'barangay' => 'Potingbato',
            'purok' => 'Purok 1',
            'address' => 'Purok 1, Barangay Potingbato, Esperanza, Masbate',
            'birthdate' => 'August 8, 1984',
            'sex' => 'Male',
            'civilStatus' => 'Married',
            'occupation' => 'Farmer',
            'residentSince' => 2009,
            'profileCompleteness' => 76,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1311',
            'firstName' => 'Precious',
            'lastName' => 'Manalo',
            'fullName' => 'Precious Domingo Manalo',
            'email' => 'precious.manalo@email.com',
            'mobile' => '0917 903 5628',
            'barangay' => 'Rizal',
            'purok' => 'Purok 2',
            'address' => 'Purok 2, Barangay Rizal, Esperanza, Masbate',
            'birthdate' => 'February 18, 2003',
            'sex' => 'Female',
            'civilStatus' => 'Single',
            'occupation' => 'College Student',
            'residentSince' => 2005,
            'profileCompleteness' => 55,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1092',
            'firstName' => 'Ernesto',
            'lastName' => 'Nierva',
            'fullName' => 'Ernesto Salazar Nierva',
            'email' => 'ernesto.nierva@email.com',
            'mobile' => '0928 340 9915',
            'barangay' => 'San Roque',
            'purok' => 'Purok 3',
            'address' => 'Purok 3, Barangay San Roque, Esperanza, Masbate',
            'birthdate' => 'June 6, 1981',
            'sex' => 'Male',
            'civilStatus' => 'Married',
            'occupation' => 'Tricycle Driver',
            'residentSince' => 2007,
            'profileCompleteness' => 70,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1167',
            'firstName' => 'Josephine',
            'lastName' => 'Olivar',
            'fullName' => 'Josephine Castro Olivar',
            'email' => 'josephine.olivar@email.com',
            'mobile' => '0919 776 2240',
            'barangay' => 'Santiago',
            'purok' => 'Purok 1',
            'address' => 'Purok 1, Barangay Santiago, Esperanza, Masbate',
            'birthdate' => 'March 27, 1990',
            'sex' => 'Female',
            'civilStatus' => 'Married',
            'occupation' => 'Seamstress',
            'residentSince' => 2015,
            'profileCompleteness' => 84,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1233',
            'firstName' => 'Ramil',
            'lastName' => 'Pascua',
            'fullName' => 'Ramil Garcia Pascua',
            'email' => 'ramil.pascua@email.com',
            'mobile' => '0906 481 6603',
            'barangay' => 'Sorosimbajan',
            'purok' => 'Purok 2',
            'address' => 'Purok 2, Barangay Sorosimbajan, Esperanza, Masbate',
            'birthdate' => 'October 5, 1993',
            'sex' => 'Male',
            'civilStatus' => 'Single',
            'occupation' => 'Fisherman',
            'residentSince' => 2020,
            'profileCompleteness' => 62,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1288',
            'firstName' => 'Liezel',
            'lastName' => 'Quimson',
            'fullName' => 'Liezel Navarro Quimson',
            'email' => 'liezel.quimson@email.com',
            'mobile' => '0917 155 8867',
            'barangay' => 'Tawad',
            'purok' => 'Purok 1',
            'address' => 'Purok 1, Barangay Tawad, Esperanza, Masbate',
            'birthdate' => 'July 19, 1994',
            'sex' => 'Female',
            'civilStatus' => 'Married',
            'occupation' => 'Sari-Sari Store Owner',
            'residentSince' => 2017,
            'profileCompleteness' => 73,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1029',
            'firstName' => 'Dante',
            'lastName' => 'Robles',
            'fullName' => 'Dante Marquez Robles',
            'email' => 'dante.robles@email.com',
            'mobile' => '0928 226 4459',
            'barangay' => 'Tunga',
            'purok' => 'Purok 2',
            'address' => 'Purok 2, Barangay Tunga, Esperanza, Masbate',
            'birthdate' => 'November 11, 1977',
            'sex' => 'Male',
            'civilStatus' => 'Married',
            'occupation' => 'Farmer',
            'residentSince' => 2003,
            'profileCompleteness' => 87,
            'status' => 'Approved',
        ],
        [
            'id' => 'ESP-RES-2024-1354',
            'firstName' => 'Cherry Ann',
            'lastName' => 'Sarmiento',
            'fullName' => 'Cherry Ann Villaflor Sarmiento',
            'email' => 'cherryann.sarmiento@email.com',
            'mobile' => '0919 447 3391',
            'barangay' => 'Villa',
            'purok' => 'Purok 3',
            'address' => 'Purok 3, Barangay Villa, Esperanza, Masbate',
            'birthdate' => 'April 4, 1996',
            'sex' => 'Female',
            'civilStatus' => 'Single',
            'occupation' => 'Public School Teacher',
            'residentSince' => 2021,
            'profileCompleteness' => 66,
            'status' => 'Approved',
        ],
    ],
];
