<?php

/**
 * Esperanza Constituent Registry — deterministic sample data.
 * Consumed by admin.constituents view. All relationships are internally
 * consistent: households ↔ families ↔ individuals share IDs.
 */

// ── Households (5) ────────────────────────────────────────────────────────────
$households = [
    [
        'id'             => 'HH-2026-001',
        'label'          => 'Bacaltos Household',
        'barangay'       => 'Poblacion',
        'sitio'          => 'Purok 2',
        'address'        => '247 Magsaysay Street, Purok 2, Brgy. Poblacion',
        'head_id'        => 'RES-2026-001',
        'head_name'      => 'Maria Fe A. Bacaltos',
        'family_ids'     => ['FAM-2026-001', 'FAM-2026-002'],
        'family_count'   => 2,
        'member_count'   => 9,
        'dwelling_type'  => 'Single Detached',
        'housing_tenure' => 'Owner',
        'electricity'    => true,
        'water'          => true,
        'toilet'         => true,
        'flood_risk'     => 'Low',
        'hazard_zone'    => 'Zone 1 (Safe)',
        'profile_pct'    => 88,
        'verification'   => 'Verified',
        'status'         => 'Active',
        'programs'       => ['4Ps', 'OSCA'],
        'tags'           => ['senior', 'youth'],
        'created'        => '2024-01-15',
        'last_updated'   => '2026-06-12',
    ],
    [
        'id'             => 'HH-2026-002',
        'label'          => 'Santos Household',
        'barangay'       => 'Masbaranon',
        'sitio'          => 'Sitio Malbog',
        'address'        => '18 Rizal Street, Sitio Malbog, Brgy. Masbaranon',
        'head_id'        => 'RES-2026-010',
        'head_name'      => 'Eduardo T. Santos',
        'family_ids'     => ['FAM-2026-003'],
        'family_count'   => 1,
        'member_count'   => 5,
        'dwelling_type'  => 'Single Attached',
        'housing_tenure' => 'Owner',
        'electricity'    => true,
        'water'          => false,
        'toilet'         => true,
        'flood_risk'     => 'Medium',
        'hazard_zone'    => 'Zone 2 (Moderate Risk)',
        'profile_pct'    => 72,
        'verification'   => 'Partially Verified',
        'status'         => 'Active',
        'programs'       => ['4Ps'],
        'tags'           => ['farmer', 'child'],
        'created'        => '2024-03-08',
        'last_updated'   => '2026-05-22',
    ],
    [
        'id'             => 'HH-2026-003',
        'label'          => 'Dela Cruz Household',
        'barangay'       => 'Baras',
        'sitio'          => 'Purok 1',
        'address'        => '12 Bonifacio Street, Purok 1, Brgy. Baras',
        'head_id'        => 'RES-2026-015',
        'head_name'      => 'Rosario P. Dela Cruz',
        'family_ids'     => ['FAM-2026-004', 'FAM-2026-005'],
        'family_count'   => 2,
        'member_count'   => 8,
        'dwelling_type'  => 'Single Detached',
        'housing_tenure' => 'Owner',
        'electricity'    => true,
        'water'          => true,
        'toilet'         => true,
        'flood_risk'     => 'Low',
        'hazard_zone'    => 'Zone 1 (Safe)',
        'profile_pct'    => 85,
        'verification'   => 'Verified',
        'status'         => 'Active',
        'programs'       => ['OSCA', 'PWD Assistance'],
        'tags'           => ['senior', 'pwd', 'infant'],
        'created'        => '2024-02-20',
        'last_updated'   => '2026-07-01',
    ],
    [
        'id'             => 'HH-2026-004',
        'label'          => 'Reyes Household',
        'barangay'       => 'Domorog',
        'sitio'          => 'Sitio Tibaon',
        'address'        => '45 Quezon Avenue, Sitio Tibaon, Brgy. Domorog',
        'head_id'        => 'RES-2026-023',
        'head_name'      => 'Andres B. Reyes',
        'family_ids'     => ['FAM-2026-006'],
        'family_count'   => 1,
        'member_count'   => 4,
        'dwelling_type'  => 'Informal Settler',
        'housing_tenure' => 'Renter',
        'electricity'    => true,
        'water'          => false,
        'toilet'         => false,
        'flood_risk'     => 'High',
        'hazard_zone'    => 'Zone 3 (High Risk)',
        'profile_pct'    => 55,
        'verification'   => 'Partially Verified',
        'status'         => 'Active',
        'programs'       => [],
        'tags'           => ['youth', 'high_risk'],
        'created'        => '2024-07-11',
        'last_updated'   => '2026-04-18',
    ],
    [
        'id'             => 'HH-2026-005',
        'label'          => 'Flores Household',
        'barangay'       => 'Magsaysay',
        'sitio'          => 'Purok 3',
        'address'        => '89 Luna Street, Purok 3, Brgy. Magsaysay',
        'head_id'        => 'RES-2026-027',
        'head_name'      => 'Grace E. Flores',
        'family_ids'     => ['FAM-2026-007'],
        'family_count'   => 1,
        'member_count'   => 3,
        'dwelling_type'  => 'Single Detached',
        'housing_tenure' => 'Owner',
        'electricity'    => true,
        'water'          => true,
        'toilet'         => true,
        'flood_risk'     => 'Low',
        'hazard_zone'    => 'Zone 1 (Safe)',
        'profile_pct'    => 78,
        'verification'   => 'Verified',
        'status'         => 'Active',
        'programs'       => ['Solo Parent', '4Ps'],
        'tags'           => ['solo_parent', 'child'],
        'created'        => '2024-09-03',
        'last_updated'   => '2026-06-28',
    ],
    // ── One-member households for each barangay's sample citizen-portal
    // resident (config/esperanza_citizens.php) — so the account a citizen
    // signs in with is also a findable, real record in the admin registry.
    ['id'=>'HH-2026-101','label'=>'Bautista Household','barangay'=>'Labangtaytay','sitio'=>'Purok 2','address'=>'Purok 2, Barangay Labangtaytay, Esperanza, Masbate','head_id'=>'RES-2026-101','head_name'=>'Ronaldo Panganiban Bautista','family_ids'=>['FAM-2026-101'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>78,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2015-01-01','last_updated'=>'2026-07-08'],
    ['id'=>'HH-2026-102','label'=>'Ferrer Household','barangay'=>'Agoho','sitio'=>'Purok 1','address'=>'Purok 1, Barangay Agoho, Esperanza, Masbate','head_id'=>'RES-2026-102','head_name'=>'Marites Gonzales Ferrer','family_ids'=>['FAM-2026-102'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>82,'verification'=>'Verified','status'=>'Active','programs'=>[],'tags'=>['farmer'],'created'=>'2010-01-01','last_updated'=>'2026-07-02'],
    ['id'=>'HH-2026-103','label'=>'Aranas Household','barangay'=>'Almero','sitio'=>'Purok 3','address'=>'Purok 3, Barangay Almero, Esperanza, Masbate','head_id'=>'RES-2026-103','head_name'=>'Joel Villanueva Aranas','family_ids'=>['FAM-2026-103'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Attached','housing_tenure'=>'Renter','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>65,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2018-01-01','last_updated'=>'2026-06-20'],
    ['id'=>'HH-2026-104','label'=>'Bonghanoy Household','barangay'=>'Baras','sitio'=>'Purok 2','address'=>'Purok 2, Barangay Baras, Esperanza, Masbate','head_id'=>'RES-2026-104','head_name'=>'Cristy Pareja Bonghanoy','family_ids'=>['FAM-2026-104'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>90,'verification'=>'Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2012-01-01','last_updated'=>'2026-07-15'],
    ['id'=>'HH-2026-105','label'=>'Cabahug Household','barangay'=>'Domorog','sitio'=>'Purok 4','address'=>'Purok 4, Barangay Domorog, Esperanza, Masbate','head_id'=>'RES-2026-105','head_name'=>'Ariel Santos Cabahug','family_ids'=>['FAM-2026-105'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>false,'toilet'=>true,'flood_risk'=>'Medium','hazard_zone'=>'Zone 2 (Moderate Risk)','profile_pct'=>71,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2008-01-01','last_updated'=>'2026-06-11'],
    ['id'=>'HH-2026-106','label'=>'Dimaano Household','barangay'=>'Guadalupe','sitio'=>'Purok 1','address'=>'Purok 1, Barangay Guadalupe, Esperanza, Masbate','head_id'=>'RES-2026-106','head_name'=>'Lorna Reyes Dimaano','family_ids'=>['FAM-2026-106'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>88,'verification'=>'Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2001-01-01','last_updated'=>'2026-07-20'],
    ['id'=>'HH-2026-107','label'=>'Espinosa Household','barangay'=>'Iligan','sitio'=>'Purok 2','address'=>'Purok 2, Barangay Iligan, Esperanza, Masbate','head_id'=>'RES-2026-107','head_name'=>'Bayani Cruz Espinosa','family_ids'=>['FAM-2026-107'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Attached','housing_tenure'=>'Renter','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>60,'verification'=>'Unverified','status'=>'Active','programs'=>[],'tags'=>['farmer'],'created'=>'2019-01-01','last_updated'=>'2026-05-30'],
    ['id'=>'HH-2026-108','label'=>'Galvez Household','barangay'=>'Labrador','sitio'=>'Purok 3','address'=>'Purok 3, Barangay Labrador, Esperanza, Masbate','head_id'=>'RES-2026-108','head_name'=>'Divina Torres Galvez','family_ids'=>['FAM-2026-108'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>95,'verification'=>'Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2011-01-01','last_updated'=>'2026-07-18'],
    ['id'=>'HH-2026-109','label'=>'Hilario Household','barangay'=>'Libertad','sitio'=>'Purok 1','address'=>'Purok 1, Barangay Libertad, Esperanza, Masbate','head_id'=>'RES-2026-109','head_name'=>'Ferdinand Ramos Hilario','family_ids'=>['FAM-2026-109'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>74,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2005-01-01','last_updated'=>'2026-06-25'],
    ['id'=>'HH-2026-110','label'=>'Ibarra Household','barangay'=>'Magsaysay','sitio'=>'Purok 5','address'=>'Purok 5, Barangay Magsaysay, Esperanza, Masbate','head_id'=>'RES-2026-110','head_name'=>'Analiza Bautista Ibarra','family_ids'=>['FAM-2026-110'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>68,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2016-01-01','last_updated'=>'2026-07-01'],
    ['id'=>'HH-2026-111','label'=>'Jacinto Household','barangay'=>'Masbaranon','sitio'=>'Purok 2','address'=>'Purok 2, Barangay Masbaranon, Esperanza, Masbate','head_id'=>'RES-2026-111','head_name'=>'Romulo Flores Jacinto','family_ids'=>['FAM-2026-111'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>80,'verification'=>'Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2013-01-01','last_updated'=>'2026-07-05'],
    ['id'=>'HH-2026-112','label'=>'Kalaw Household','barangay'=>'Poblacion','sitio'=>'Purok 6','address'=>'Purok 6, Barangay Poblacion, Esperanza, Masbate','head_id'=>'RES-2026-112','head_name'=>'Grace Mendoza Kalaw','family_ids'=>['FAM-2026-112'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>92,'verification'=>'Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2014-01-01','last_updated'=>'2026-07-22'],
    ['id'=>'HH-2026-113','label'=>'Lazaro Household','barangay'=>'Potingbato','sitio'=>'Purok 1','address'=>'Purok 1, Barangay Potingbato, Esperanza, Masbate','head_id'=>'RES-2026-113','head_name'=>'Danilo Aquino Lazaro','family_ids'=>['FAM-2026-113'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>76,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'tags'=>['farmer'],'created'=>'2009-01-01','last_updated'=>'2026-06-30'],
    ['id'=>'HH-2026-114','label'=>'Manalo Household','barangay'=>'Rizal','sitio'=>'Purok 2','address'=>'Purok 2, Barangay Rizal, Esperanza, Masbate','head_id'=>'RES-2026-114','head_name'=>'Precious Domingo Manalo','family_ids'=>['FAM-2026-114'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>55,'verification'=>'For Validation','status'=>'Active','programs'=>[],'tags'=>['youth'],'created'=>'2005-01-01','last_updated'=>'2026-05-15'],
    ['id'=>'HH-2026-115','label'=>'Nierva Household','barangay'=>'San Roque','sitio'=>'Purok 3','address'=>'Purok 3, Barangay San Roque, Esperanza, Masbate','head_id'=>'RES-2026-115','head_name'=>'Ernesto Salazar Nierva','family_ids'=>['FAM-2026-115'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Attached','housing_tenure'=>'Renter','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>70,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2007-01-01','last_updated'=>'2026-06-08'],
    ['id'=>'HH-2026-116','label'=>'Olivar Household','barangay'=>'Santiago','sitio'=>'Purok 1','address'=>'Purok 1, Barangay Santiago, Esperanza, Masbate','head_id'=>'RES-2026-116','head_name'=>'Josephine Castro Olivar','family_ids'=>['FAM-2026-116'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>84,'verification'=>'Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2015-01-01','last_updated'=>'2026-07-12'],
    ['id'=>'HH-2026-117','label'=>'Pascua Household','barangay'=>'Sorosimbajan','sitio'=>'Purok 2','address'=>'Purok 2, Barangay Sorosimbajan, Esperanza, Masbate','head_id'=>'RES-2026-117','head_name'=>'Ramil Garcia Pascua','family_ids'=>['FAM-2026-117'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>62,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2020-01-01','last_updated'=>'2026-06-02'],
    ['id'=>'HH-2026-118','label'=>'Quimson Household','barangay'=>'Tawad','sitio'=>'Purok 1','address'=>'Purok 1, Barangay Tawad, Esperanza, Masbate','head_id'=>'RES-2026-118','head_name'=>'Liezel Navarro Quimson','family_ids'=>['FAM-2026-118'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>73,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'tags'=>[],'created'=>'2017-01-01','last_updated'=>'2026-06-27'],
    ['id'=>'HH-2026-119','label'=>'Robles Household','barangay'=>'Tunga','sitio'=>'Purok 2','address'=>'Purok 2, Barangay Tunga, Esperanza, Masbate','head_id'=>'RES-2026-119','head_name'=>'Dante Marquez Robles','family_ids'=>['FAM-2026-119'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Owner','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>87,'verification'=>'Verified','status'=>'Active','programs'=>[],'tags'=>['farmer'],'created'=>'2003-01-01','last_updated'=>'2026-07-10'],
    ['id'=>'HH-2026-120','label'=>'Sarmiento Household','barangay'=>'Villa','sitio'=>'Purok 3','address'=>'Purok 3, Barangay Villa, Esperanza, Masbate','head_id'=>'RES-2026-120','head_name'=>'Cherry Ann Villaflor Sarmiento','family_ids'=>['FAM-2026-120'],'family_count'=>1,'member_count'=>1,'dwelling_type'=>'Single Detached','housing_tenure'=>'Renter','electricity'=>true,'water'=>true,'toilet'=>true,'flood_risk'=>'Low','hazard_zone'=>'Zone 1 (Safe)','profile_pct'=>66,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'tags'=>['youth'],'created'=>'2021-01-01','last_updated'=>'2026-06-18'],
];

// ── Families (7) ──────────────────────────────────────────────────────────────
$families = [
    [
        'id'           => 'FAM-2026-001',
        'label'        => 'Bacaltos Family',
        'surname'      => 'Bacaltos',
        'family_type'  => 'Nuclear',
        'barangay'     => 'Poblacion',
        'sitio'        => 'Purok 2',
        'household_id' => 'HH-2026-001',
        'head_id'      => 'RES-2026-001',
        'head_name'    => 'Maria Fe A. Bacaltos',
        'member_ids'   => ['RES-2026-001','RES-2026-002','RES-2026-003','RES-2026-004','RES-2026-005'],
        'member_count' => 5,
        'profile_pct'  => 86,
        'verification' => 'Verified',
        'status'       => 'Active',
        'programs'     => ['4Ps', 'OSCA'],
        'notes'        => 'Head is a widow, senior citizen, sole provider for 4 children.',
        'created'      => '2024-01-15',
        'last_updated' => '2026-06-12',
    ],
    [
        'id'           => 'FAM-2026-002',
        'label'        => 'Villanueva Family',
        'surname'      => 'Villanueva',
        'family_type'  => 'Extended',
        'barangay'     => 'Poblacion',
        'sitio'        => 'Purok 2',
        'household_id' => 'HH-2026-001',
        'head_id'      => 'RES-2026-006',
        'head_name'    => 'Carlos T. Villanueva',
        'member_ids'   => ['RES-2026-006','RES-2026-007','RES-2026-008','RES-2026-009'],
        'member_count' => 4,
        'profile_pct'  => 75,
        'verification' => 'Partially Verified',
        'status'       => 'Active',
        'programs'     => [],
        'notes'        => 'Extended relatives of the Bacaltos family sharing the same compound.',
        'created'      => '2024-01-15',
        'last_updated' => '2026-05-08',
    ],
    [
        'id'           => 'FAM-2026-003',
        'label'        => 'Santos Family',
        'surname'      => 'Santos',
        'family_type'  => 'Nuclear',
        'barangay'     => 'Masbaranon',
        'sitio'        => 'Sitio Malbog',
        'household_id' => 'HH-2026-002',
        'head_id'      => 'RES-2026-010',
        'head_name'    => 'Eduardo T. Santos',
        'member_ids'   => ['RES-2026-010','RES-2026-011','RES-2026-012','RES-2026-013'],
        'member_count' => 4,
        'profile_pct'  => 79,
        'verification' => 'Verified',
        'status'       => 'Active',
        'programs'     => ['4Ps'],
        'notes'        => 'Farming family; 2 minor children enrolled in school.',
        'created'      => '2024-03-08',
        'last_updated' => '2026-05-22',
    ],
    [
        'id'           => 'FAM-2026-004',
        'label'        => 'Dela Cruz Family',
        'surname'      => 'Dela Cruz',
        'family_type'  => 'Nuclear',
        'barangay'     => 'Baras',
        'sitio'        => 'Purok 1',
        'household_id' => 'HH-2026-003',
        'head_id'      => 'RES-2026-015',
        'head_name'    => 'Rosario P. Dela Cruz',
        'member_ids'   => ['RES-2026-015','RES-2026-016','RES-2026-017','RES-2026-021'],
        'member_count' => 4,
        'profile_pct'  => 91,
        'verification' => 'Verified',
        'status'       => 'Active',
        'programs'     => ['OSCA', 'PWD Assistance'],
        'notes'        => 'Senior citizen couple; one PWD son living with them.',
        'created'      => '2024-02-20',
        'last_updated' => '2026-07-01',
    ],
    [
        'id'           => 'FAM-2026-005',
        'label'        => 'Dela Cruz-Umali Family',
        'surname'      => 'Dela Cruz-Umali',
        'family_type'  => 'Nuclear',
        'barangay'     => 'Baras',
        'sitio'        => 'Purok 1',
        'household_id' => 'HH-2026-003',
        'head_id'      => 'RES-2026-018',
        'head_name'    => 'Lourdes D. Dela Cruz-Umali',
        'member_ids'   => ['RES-2026-018','RES-2026-019','RES-2026-020','RES-2026-022'],
        'member_count' => 4,
        'profile_pct'  => 76,
        'verification' => 'Partially Verified',
        'status'       => 'Active',
        'programs'     => [],
        'notes'        => 'Daughter of the Dela Cruz seniors; lives in the same compound with husband and 2 young children.',
        'created'      => '2024-04-10',
        'last_updated' => '2026-06-15',
    ],
    [
        'id'           => 'FAM-2026-006',
        'label'        => 'Reyes Family',
        'surname'      => 'Reyes',
        'family_type'  => 'Nuclear',
        'barangay'     => 'Domorog',
        'sitio'        => 'Sitio Tibaon',
        'household_id' => 'HH-2026-004',
        'head_id'      => 'RES-2026-023',
        'head_name'    => 'Andres B. Reyes',
        'member_ids'   => ['RES-2026-023','RES-2026-024','RES-2026-025','RES-2026-026'],
        'member_count' => 4,
        'profile_pct'  => 58,
        'verification' => 'Partially Verified',
        'status'       => 'Active',
        'programs'     => [],
        'notes'        => 'Located in a high flood-risk zone. Two out-of-school youth.',
        'created'      => '2024-07-11',
        'last_updated' => '2026-04-18',
    ],
    [
        'id'           => 'FAM-2026-007',
        'label'        => 'Flores Family',
        'surname'      => 'Flores',
        'family_type'  => 'Single Parent',
        'barangay'     => 'Magsaysay',
        'sitio'        => 'Purok 3',
        'household_id' => 'HH-2026-005',
        'head_id'      => 'RES-2026-027',
        'head_name'    => 'Grace E. Flores',
        'member_ids'   => ['RES-2026-027','RES-2026-028','RES-2026-029'],
        'member_count' => 3,
        'profile_pct'  => 80,
        'verification' => 'Verified',
        'status'       => 'Active',
        'programs'     => ['Solo Parent', '4Ps'],
        'notes'        => 'Solo parent; head is separated, raising 2 minor children.',
        'created'      => '2024-09-03',
        'last_updated' => '2026-06-28',
    ],
    // ── One per barangay's sample citizen-portal resident (see matching
    // household note above) ──────────────────────────────────────────────
    ['id'=>'FAM-2026-101','label'=>'Bautista Family','surname'=>'Bautista','family_type'=>'Single','barangay'=>'Labangtaytay','sitio'=>'Purok 2','household_id'=>'HH-2026-101','head_id'=>'RES-2026-101','head_name'=>'Ronaldo Panganiban Bautista','member_ids'=>['RES-2026-101'],'member_count'=>1,'profile_pct'=>78,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Labangtaytay.','created'=>'2015-01-01','last_updated'=>'2026-07-08'],
    ['id'=>'FAM-2026-102','label'=>'Ferrer Family','surname'=>'Ferrer','family_type'=>'Single','barangay'=>'Agoho','sitio'=>'Purok 1','household_id'=>'HH-2026-102','head_id'=>'RES-2026-102','head_name'=>'Marites Gonzales Ferrer','member_ids'=>['RES-2026-102'],'member_count'=>1,'profile_pct'=>82,'verification'=>'Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Agoho.','created'=>'2010-01-01','last_updated'=>'2026-07-02'],
    ['id'=>'FAM-2026-103','label'=>'Aranas Family','surname'=>'Aranas','family_type'=>'Single','barangay'=>'Almero','sitio'=>'Purok 3','household_id'=>'HH-2026-103','head_id'=>'RES-2026-103','head_name'=>'Joel Villanueva Aranas','member_ids'=>['RES-2026-103'],'member_count'=>1,'profile_pct'=>65,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Almero.','created'=>'2018-01-01','last_updated'=>'2026-06-20'],
    ['id'=>'FAM-2026-104','label'=>'Bonghanoy Family','surname'=>'Bonghanoy','family_type'=>'Single','barangay'=>'Baras','sitio'=>'Purok 2','household_id'=>'HH-2026-104','head_id'=>'RES-2026-104','head_name'=>'Cristy Pareja Bonghanoy','member_ids'=>['RES-2026-104'],'member_count'=>1,'profile_pct'=>90,'verification'=>'Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Baras.','created'=>'2012-01-01','last_updated'=>'2026-07-15'],
    ['id'=>'FAM-2026-105','label'=>'Cabahug Family','surname'=>'Cabahug','family_type'=>'Single','barangay'=>'Domorog','sitio'=>'Purok 4','household_id'=>'HH-2026-105','head_id'=>'RES-2026-105','head_name'=>'Ariel Santos Cabahug','member_ids'=>['RES-2026-105'],'member_count'=>1,'profile_pct'=>71,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Domorog.','created'=>'2008-01-01','last_updated'=>'2026-06-11'],
    ['id'=>'FAM-2026-106','label'=>'Dimaano Family','surname'=>'Dimaano','family_type'=>'Single','barangay'=>'Guadalupe','sitio'=>'Purok 1','household_id'=>'HH-2026-106','head_id'=>'RES-2026-106','head_name'=>'Lorna Reyes Dimaano','member_ids'=>['RES-2026-106'],'member_count'=>1,'profile_pct'=>88,'verification'=>'Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Guadalupe.','created'=>'2001-01-01','last_updated'=>'2026-07-20'],
    ['id'=>'FAM-2026-107','label'=>'Espinosa Family','surname'=>'Espinosa','family_type'=>'Single','barangay'=>'Iligan','sitio'=>'Purok 2','household_id'=>'HH-2026-107','head_id'=>'RES-2026-107','head_name'=>'Bayani Cruz Espinosa','member_ids'=>['RES-2026-107'],'member_count'=>1,'profile_pct'=>60,'verification'=>'Unverified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Iligan.','created'=>'2019-01-01','last_updated'=>'2026-05-30'],
    ['id'=>'FAM-2026-108','label'=>'Galvez Family','surname'=>'Galvez','family_type'=>'Single','barangay'=>'Labrador','sitio'=>'Purok 3','household_id'=>'HH-2026-108','head_id'=>'RES-2026-108','head_name'=>'Divina Torres Galvez','member_ids'=>['RES-2026-108'],'member_count'=>1,'profile_pct'=>95,'verification'=>'Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Labrador.','created'=>'2011-01-01','last_updated'=>'2026-07-18'],
    ['id'=>'FAM-2026-109','label'=>'Hilario Family','surname'=>'Hilario','family_type'=>'Single','barangay'=>'Libertad','sitio'=>'Purok 1','household_id'=>'HH-2026-109','head_id'=>'RES-2026-109','head_name'=>'Ferdinand Ramos Hilario','member_ids'=>['RES-2026-109'],'member_count'=>1,'profile_pct'=>74,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Libertad.','created'=>'2005-01-01','last_updated'=>'2026-06-25'],
    ['id'=>'FAM-2026-110','label'=>'Ibarra Family','surname'=>'Ibarra','family_type'=>'Single','barangay'=>'Magsaysay','sitio'=>'Purok 5','household_id'=>'HH-2026-110','head_id'=>'RES-2026-110','head_name'=>'Analiza Bautista Ibarra','member_ids'=>['RES-2026-110'],'member_count'=>1,'profile_pct'=>68,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Magsaysay.','created'=>'2016-01-01','last_updated'=>'2026-07-01'],
    ['id'=>'FAM-2026-111','label'=>'Jacinto Family','surname'=>'Jacinto','family_type'=>'Single','barangay'=>'Masbaranon','sitio'=>'Purok 2','household_id'=>'HH-2026-111','head_id'=>'RES-2026-111','head_name'=>'Romulo Flores Jacinto','member_ids'=>['RES-2026-111'],'member_count'=>1,'profile_pct'=>80,'verification'=>'Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Masbaranon.','created'=>'2013-01-01','last_updated'=>'2026-07-05'],
    ['id'=>'FAM-2026-112','label'=>'Kalaw Family','surname'=>'Kalaw','family_type'=>'Single','barangay'=>'Poblacion','sitio'=>'Purok 6','household_id'=>'HH-2026-112','head_id'=>'RES-2026-112','head_name'=>'Grace Mendoza Kalaw','member_ids'=>['RES-2026-112'],'member_count'=>1,'profile_pct'=>92,'verification'=>'Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Poblacion.','created'=>'2014-01-01','last_updated'=>'2026-07-22'],
    ['id'=>'FAM-2026-113','label'=>'Lazaro Family','surname'=>'Lazaro','family_type'=>'Single','barangay'=>'Potingbato','sitio'=>'Purok 1','household_id'=>'HH-2026-113','head_id'=>'RES-2026-113','head_name'=>'Danilo Aquino Lazaro','member_ids'=>['RES-2026-113'],'member_count'=>1,'profile_pct'=>76,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Potingbato.','created'=>'2009-01-01','last_updated'=>'2026-06-30'],
    ['id'=>'FAM-2026-114','label'=>'Manalo Family','surname'=>'Manalo','family_type'=>'Single','barangay'=>'Rizal','sitio'=>'Purok 2','household_id'=>'HH-2026-114','head_id'=>'RES-2026-114','head_name'=>'Precious Domingo Manalo','member_ids'=>['RES-2026-114'],'member_count'=>1,'profile_pct'=>55,'verification'=>'For Validation','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Rizal.','created'=>'2005-01-01','last_updated'=>'2026-05-15'],
    ['id'=>'FAM-2026-115','label'=>'Nierva Family','surname'=>'Nierva','family_type'=>'Single','barangay'=>'San Roque','sitio'=>'Purok 3','household_id'=>'HH-2026-115','head_id'=>'RES-2026-115','head_name'=>'Ernesto Salazar Nierva','member_ids'=>['RES-2026-115'],'member_count'=>1,'profile_pct'=>70,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay San Roque.','created'=>'2007-01-01','last_updated'=>'2026-06-08'],
    ['id'=>'FAM-2026-116','label'=>'Olivar Family','surname'=>'Olivar','family_type'=>'Single','barangay'=>'Santiago','sitio'=>'Purok 1','household_id'=>'HH-2026-116','head_id'=>'RES-2026-116','head_name'=>'Josephine Castro Olivar','member_ids'=>['RES-2026-116'],'member_count'=>1,'profile_pct'=>84,'verification'=>'Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Santiago.','created'=>'2015-01-01','last_updated'=>'2026-07-12'],
    ['id'=>'FAM-2026-117','label'=>'Pascua Family','surname'=>'Pascua','family_type'=>'Single','barangay'=>'Sorosimbajan','sitio'=>'Purok 2','household_id'=>'HH-2026-117','head_id'=>'RES-2026-117','head_name'=>'Ramil Garcia Pascua','member_ids'=>['RES-2026-117'],'member_count'=>1,'profile_pct'=>62,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Sorosimbajan.','created'=>'2020-01-01','last_updated'=>'2026-06-02'],
    ['id'=>'FAM-2026-118','label'=>'Quimson Family','surname'=>'Quimson','family_type'=>'Single','barangay'=>'Tawad','sitio'=>'Purok 1','household_id'=>'HH-2026-118','head_id'=>'RES-2026-118','head_name'=>'Liezel Navarro Quimson','member_ids'=>['RES-2026-118'],'member_count'=>1,'profile_pct'=>73,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Tawad.','created'=>'2017-01-01','last_updated'=>'2026-06-27'],
    ['id'=>'FAM-2026-119','label'=>'Robles Family','surname'=>'Robles','family_type'=>'Single','barangay'=>'Tunga','sitio'=>'Purok 2','household_id'=>'HH-2026-119','head_id'=>'RES-2026-119','head_name'=>'Dante Marquez Robles','member_ids'=>['RES-2026-119'],'member_count'=>1,'profile_pct'=>87,'verification'=>'Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Tunga.','created'=>'2003-01-01','last_updated'=>'2026-07-10'],
    ['id'=>'FAM-2026-120','label'=>'Sarmiento Family','surname'=>'Sarmiento','family_type'=>'Single','barangay'=>'Villa','sitio'=>'Purok 3','household_id'=>'HH-2026-120','head_id'=>'RES-2026-120','head_name'=>'Cherry Ann Villaflor Sarmiento','member_ids'=>['RES-2026-120'],'member_count'=>1,'profile_pct'=>66,'verification'=>'Partially Verified','status'=>'Active','programs'=>[],'notes'=>'Citizen Portal sample resident for Barangay Villa.','created'=>'2021-01-01','last_updated'=>'2026-06-18'],
];

// ── Individuals (31 records) ──────────────────────────────────────────────────
$individuals = [
    // HH-001 / FAM-001 Bacaltos Nuclear
    ['id'=>'RES-2026-001','name'=>'Maria Fe A. Bacaltos','sex'=>'Female','age'=>62,'dob'=>'1963-08-14','civil_status'=>'Widow','barangay'=>'Poblacion','sitio'=>'Purok 2','household_id'=>'HH-2026-001','family_id'=>'FAM-2026-001','relation'=>'Head','contact'=>'0917 342 8810','occupation'=>'Sari-sari Store Owner','education'=>'Elementary Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>['senior','osca'],'verification'=>'Verified','profile_pct'=>94,'status'=>'Active','created'=>'2024-01-15','last_updated'=>'2026-06-12','emergency'=>['name'=>'Jose Bacaltos Jr.','contact'=>'0917 342 8811','relation'=>'Son'],'services'=>[['date'=>'2026-03-10','type'=>'OSCA ID Renewal','status'=>'Completed'],['date'=>'2025-11-02','type'=>'Certificate of Indigency','status'=>'Completed']]],
    ['id'=>'RES-2026-002','name'=>'Jose A. Bacaltos Jr.','sex'=>'Male','age'=>29,'dob'=>'1996-11-07','civil_status'=>'Single','barangay'=>'Poblacion','sitio'=>'Purok 2','household_id'=>'HH-2026-001','family_id'=>'FAM-2026-001','relation'=>'Son','contact'=>'0917 342 8811','occupation'=>'Construction Worker','education'=>'Senior High School Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>[],'verification'=>'Verified','profile_pct'=>88,'status'=>'Active','created'=>'2024-01-15','last_updated'=>'2026-04-20','emergency'=>['name'=>'Maria Fe A. Bacaltos','contact'=>'0917 342 8810','relation'=>'Mother'],'services'=>[['date'=>'2025-08-15','type'=>'Barangay Clearance','status'=>'Completed']]],
    ['id'=>'RES-2026-003','name'=>'Anna Marie A. Bacaltos','sex'=>'Female','age'=>26,'dob'=>'1999-04-22','civil_status'=>'Single','barangay'=>'Poblacion','sitio'=>'Purok 2','household_id'=>'HH-2026-001','family_id'=>'FAM-2026-001','relation'=>'Daughter','contact'=>null,'occupation'=>'Student (College)','education'=>'College Undergraduate','income_range'=>'None','tags'=>['4ps'],'verification'=>'Verified','profile_pct'=>82,'status'=>'Active','created'=>'2024-01-15','last_updated'=>'2026-03-05','emergency'=>['name'=>'Maria Fe A. Bacaltos','contact'=>'0917 342 8810','relation'=>'Mother'],'services'=>[['date'=>'2026-02-10','type'=>'4Ps Educational Assistance','status'=>'Completed']]],
    ['id'=>'RES-2026-004','name'=>'Marco A. Bacaltos','sex'=>'Male','age'=>23,'dob'=>'2002-09-30','civil_status'=>'Single','barangay'=>'Poblacion','sitio'=>'Purok 2','household_id'=>'HH-2026-001','family_id'=>'FAM-2026-001','relation'=>'Son','contact'=>null,'occupation'=>'Unemployed','education'=>'Junior High School Graduate','income_range'=>'None','tags'=>['youth','osy'],'verification'=>'Partially Verified','profile_pct'=>60,'status'=>'Active','created'=>'2024-01-15','last_updated'=>'2025-11-14','emergency'=>['name'=>'Maria Fe A. Bacaltos','contact'=>'0917 342 8810','relation'=>'Mother'],'services'=>[]],
    ['id'=>'RES-2026-005','name'=>'Lucia A. Bacaltos','sex'=>'Female','age'=>19,'dob'=>'2006-02-14','civil_status'=>'Single','barangay'=>'Poblacion','sitio'=>'Purok 2','household_id'=>'HH-2026-001','family_id'=>'FAM-2026-001','relation'=>'Daughter','contact'=>null,'occupation'=>'Student (Senior High)','education'=>'Senior High School (Current)','income_range'=>'None','tags'=>['youth','4ps'],'verification'=>'For Validation','profile_pct'=>45,'status'=>'Active','created'=>'2024-08-20','last_updated'=>'2025-09-10','emergency'=>['name'=>'Maria Fe A. Bacaltos','contact'=>'0917 342 8810','relation'=>'Mother'],'services'=>[]],
    // HH-001 / FAM-002 Villanueva Extended
    ['id'=>'RES-2026-006','name'=>'Carlos T. Villanueva','sex'=>'Male','age'=>46,'dob'=>'1979-06-03','civil_status'=>'Married','barangay'=>'Poblacion','sitio'=>'Purok 2','household_id'=>'HH-2026-001','family_id'=>'FAM-2026-002','relation'=>'Head','contact'=>'0918 445 6672','occupation'=>'Tricycle Driver','education'=>'High School Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>[],'verification'=>'Verified','profile_pct'=>90,'status'=>'Active','created'=>'2024-01-15','last_updated'=>'2026-05-08','emergency'=>['name'=>'Teresita B. Villanueva','contact'=>'0918 445 6673','relation'=>'Spouse'],'services'=>[['date'=>'2026-01-18','type'=>'Barangay Clearance','status'=>'Completed']]],
    ['id'=>'RES-2026-007','name'=>'Teresita B. Villanueva','sex'=>'Female','age'=>43,'dob'=>'1982-12-19','civil_status'=>'Married','barangay'=>'Poblacion','sitio'=>'Purok 2','household_id'=>'HH-2026-001','family_id'=>'FAM-2026-002','relation'=>'Spouse','contact'=>'0918 445 6673','occupation'=>'Laundrywoman','education'=>'High School Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>[],'verification'=>'Verified','profile_pct'=>85,'status'=>'Active','created'=>'2024-01-15','last_updated'=>'2026-04-15','emergency'=>['name'=>'Carlos T. Villanueva','contact'=>'0918 445 6672','relation'=>'Spouse'],'services'=>[]],
    ['id'=>'RES-2026-008','name'=>'Gina T. Villanueva','sex'=>'Female','age'=>21,'dob'=>'2004-07-08','civil_status'=>'Single','barangay'=>'Poblacion','sitio'=>'Purok 2','household_id'=>'HH-2026-001','family_id'=>'FAM-2026-002','relation'=>'Daughter','contact'=>null,'occupation'=>'Vendor (Street)','education'=>'Senior High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>['youth'],'verification'=>'Partially Verified','profile_pct'=>58,'status'=>'Active','created'=>'2024-06-12','last_updated'=>'2025-12-01','emergency'=>['name'=>'Carlos T. Villanueva','contact'=>'0918 445 6672','relation'=>'Father'],'services'=>[]],
    ['id'=>'RES-2026-009','name'=>'Rico T. Villanueva','sex'=>'Male','age'=>17,'dob'=>'2008-10-25','civil_status'=>'Single','barangay'=>'Poblacion','sitio'=>'Purok 2','household_id'=>'HH-2026-001','family_id'=>'FAM-2026-002','relation'=>'Son','contact'=>null,'occupation'=>'Student (Junior High)','education'=>'Junior High School (Current)','income_range'=>'None','tags'=>['youth','child'],'verification'=>'Unverified','profile_pct'=>30,'status'=>'Active','created'=>'2024-06-12','last_updated'=>'2024-11-20','emergency'=>['name'=>'Carlos T. Villanueva','contact'=>'0918 445 6672','relation'=>'Father'],'services'=>[]],
    // HH-002 / FAM-003 Santos Nuclear
    ['id'=>'RES-2026-010','name'=>'Eduardo T. Santos','sex'=>'Male','age'=>39,'dob'=>'1986-05-28','civil_status'=>'Married','barangay'=>'Masbaranon','sitio'=>'Sitio Malbog','household_id'=>'HH-2026-002','family_id'=>'FAM-2026-003','relation'=>'Head','contact'=>'0928 512 4401','occupation'=>'Farmer','education'=>'Elementary Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>['4ps','farmer'],'verification'=>'Verified','profile_pct'=>88,'status'=>'Active','created'=>'2024-03-08','last_updated'=>'2026-05-22','emergency'=>['name'=>'Consuelo L. Santos','contact'=>'0928 512 4402','relation'=>'Spouse'],'services'=>[['date'=>'2026-04-10','type'=>'4Ps Monitoring Visit','status'=>'Completed'],['date'=>'2025-10-22','type'=>'Certificate of Residency','status'=>'Completed']]],
    ['id'=>'RES-2026-011','name'=>'Consuelo L. Santos','sex'=>'Female','age'=>36,'dob'=>'1989-02-14','civil_status'=>'Married','barangay'=>'Masbaranon','sitio'=>'Sitio Malbog','household_id'=>'HH-2026-002','family_id'=>'FAM-2026-003','relation'=>'Spouse','contact'=>'0928 512 4402','occupation'=>'Farmer / Housewife','education'=>'Elementary Graduate','income_range'=>'Below ₱5,000/mo','tags'=>['4ps'],'verification'=>'Verified','profile_pct'=>82,'status'=>'Active','created'=>'2024-03-08','last_updated'=>'2026-05-22','emergency'=>['name'=>'Eduardo T. Santos','contact'=>'0928 512 4401','relation'=>'Spouse'],'services'=>[]],
    ['id'=>'RES-2026-012','name'=>'Paolo E. Santos','sex'=>'Male','age'=>15,'dob'=>'2010-08-08','civil_status'=>'Single','barangay'=>'Masbaranon','sitio'=>'Sitio Malbog','household_id'=>'HH-2026-002','family_id'=>'FAM-2026-003','relation'=>'Son','contact'=>null,'occupation'=>'Student (Junior High)','education'=>'Junior High School (Current)','income_range'=>'None','tags'=>['youth','child','4ps'],'verification'=>'Unverified','profile_pct'=>40,'status'=>'Active','created'=>'2024-03-08','last_updated'=>'2025-07-14','emergency'=>['name'=>'Eduardo T. Santos','contact'=>'0928 512 4401','relation'=>'Father'],'services'=>[]],
    ['id'=>'RES-2026-013','name'=>'Sophia E. Santos','sex'=>'Female','age'=>11,'dob'=>'2014-12-03','civil_status'=>'Single','barangay'=>'Masbaranon','sitio'=>'Sitio Malbog','household_id'=>'HH-2026-002','family_id'=>'FAM-2026-003','relation'=>'Daughter','contact'=>null,'occupation'=>'Student (Elementary)','education'=>'Elementary (Current)','income_range'=>'None','tags'=>['child','4ps'],'verification'=>'Unverified','profile_pct'=>35,'status'=>'Active','created'=>'2024-03-08','last_updated'=>'2025-06-01','emergency'=>['name'=>'Eduardo T. Santos','contact'=>'0928 512 4401','relation'=>'Father'],'services'=>[]],
    ['id'=>'RES-2026-014','name'=>'Roberto M. Aquino','sex'=>'Male','age'=>30,'dob'=>'1995-03-16','civil_status'=>'Single','barangay'=>'Masbaranon','sitio'=>'Sitio Malbog','household_id'=>'HH-2026-002','family_id'=>null,'relation'=>'Boarder','contact'=>'0906 778 3302','occupation'=>'Informal Worker','education'=>'Junior High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>[],'verification'=>'Unverified','profile_pct'=>28,'status'=>'Active','created'=>'2025-01-10','last_updated'=>'2025-04-05','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    // HH-003 / FAM-004 Dela Cruz Nuclear (Senior)
    ['id'=>'RES-2026-015','name'=>'Rosario P. Dela Cruz','sex'=>'Female','age'=>63,'dob'=>'1962-10-11','civil_status'=>'Married','barangay'=>'Baras','sitio'=>'Purok 1','household_id'=>'HH-2026-003','family_id'=>'FAM-2026-004','relation'=>'Head','contact'=>'0927 441 0082','occupation'=>'Housewife (Retired)','education'=>'Elementary Graduate','income_range'=>'Below ₱5,000/mo','tags'=>['senior','osca'],'verification'=>'Verified','profile_pct'=>91,'status'=>'Active','created'=>'2024-02-20','last_updated'=>'2026-07-01','emergency'=>['name'=>'Ramon C. Dela Cruz','contact'=>'0927 441 0083','relation'=>'Spouse'],'services'=>[['date'=>'2026-05-18','type'=>'OSCA ID Renewal','status'=>'Completed'],['date'=>'2025-12-10','type'=>'Social Pension (ISC)','status'=>'Completed']]],
    ['id'=>'RES-2026-016','name'=>'Ramon C. Dela Cruz','sex'=>'Male','age'=>66,'dob'=>'1959-07-22','civil_status'=>'Married','barangay'=>'Baras','sitio'=>'Purok 1','household_id'=>'HH-2026-003','family_id'=>'FAM-2026-004','relation'=>'Spouse','contact'=>'0927 441 0083','occupation'=>'Retired (Fisherman)','education'=>'Elementary Graduate','income_range'=>'Below ₱5,000/mo','tags'=>['senior','osca'],'verification'=>'Verified','profile_pct'=>88,'status'=>'Active','created'=>'2024-02-20','last_updated'=>'2026-07-01','emergency'=>['name'=>'Rosario P. Dela Cruz','contact'=>'0927 441 0082','relation'=>'Spouse'],'services'=>[['date'=>'2026-05-18','type'=>'OSCA ID Renewal','status'=>'Completed']]],
    ['id'=>'RES-2026-017','name'=>'Bernardo R. Dela Cruz','sex'=>'Male','age'=>34,'dob'=>'1991-04-18','civil_status'=>'Single','barangay'=>'Baras','sitio'=>'Purok 1','household_id'=>'HH-2026-003','family_id'=>'FAM-2026-004','relation'=>'Son','contact'=>'0927 441 0085','occupation'=>'Self-employed (Home-based)','education'=>'Senior High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>['pwd'],'verification'=>'Verified','profile_pct'=>75,'status'=>'Active','created'=>'2024-02-20','last_updated'=>'2026-03-14','emergency'=>['name'=>'Rosario P. Dela Cruz','contact'=>'0927 441 0082','relation'=>'Mother'],'services'=>[['date'=>'2025-09-05','type'=>'PWD ID Application','status'=>'Completed'],['date'=>'2025-06-22','type'=>'PWD Cash Assistance','status'=>'Completed']]],
    ['id'=>'RES-2026-021','name'=>'Benjamin R. Dela Cruz','sex'=>'Male','age'=>29,'dob'=>'1996-08-18','civil_status'=>'Single','barangay'=>'Baras','sitio'=>'Purok 1','household_id'=>'HH-2026-003','family_id'=>'FAM-2026-004','relation'=>'Son','contact'=>null,'occupation'=>'Farmer','education'=>'High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>[],'verification'=>'Unverified','profile_pct'=>32,'status'=>'Active','created'=>'2025-02-04','last_updated'=>'2025-05-01','emergency'=>['name'=>'Rosario P. Dela Cruz','contact'=>'0927 441 0082','relation'=>'Mother'],'services'=>[]],
    // HH-003 / FAM-005 Dela Cruz-Umali
    ['id'=>'RES-2026-018','name'=>'Lourdes D. Dela Cruz-Umali','sex'=>'Female','age'=>31,'dob'=>'1994-09-01','civil_status'=>'Married','barangay'=>'Baras','sitio'=>'Purok 1','household_id'=>'HH-2026-003','family_id'=>'FAM-2026-005','relation'=>'Head','contact'=>'0916 830 2200','occupation'=>'Teacher (Private School)','education'=>'College Graduate (BSEd)','income_range'=>'Middle (₱10,001–₱20,000/mo)','tags'=>[],'verification'=>'Verified','profile_pct'=>82,'status'=>'Active','created'=>'2024-04-10','last_updated'=>'2026-06-15','emergency'=>['name'=>'Carlos A. Umali','contact'=>'0916 830 2201','relation'=>'Spouse'],'services'=>[['date'=>'2026-02-14','type'=>'Certificate of Residency','status'=>'Completed']]],
    ['id'=>'RES-2026-019','name'=>'Carlos A. Umali','sex'=>'Male','age'=>34,'dob'=>'1991-11-30','civil_status'=>'Married','barangay'=>'Baras','sitio'=>'Purok 1','household_id'=>'HH-2026-003','family_id'=>'FAM-2026-005','relation'=>'Spouse','contact'=>'0916 830 2201','occupation'=>'Government Employee (LGU)','education'=>'College Graduate (BSBA)','income_range'=>'Middle (₱10,001–₱20,000/mo)','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>65,'status'=>'Active','created'=>'2024-04-10','last_updated'=>'2025-10-08','emergency'=>['name'=>'Lourdes D. Dela Cruz-Umali','contact'=>'0916 830 2200','relation'=>'Spouse'],'services'=>[]],
    ['id'=>'RES-2026-020','name'=>'Sofia L. Umali','sex'=>'Female','age'=>6,'dob'=>'2019-06-12','civil_status'=>'Single','barangay'=>'Baras','sitio'=>'Purok 1','household_id'=>'HH-2026-003','family_id'=>'FAM-2026-005','relation'=>'Daughter','contact'=>null,'occupation'=>'Student (Elementary)','education'=>'Elementary (Current)','income_range'=>'None','tags'=>['child'],'verification'=>'Unverified','profile_pct'=>38,'status'=>'Active','created'=>'2024-07-20','last_updated'=>'2025-03-10','emergency'=>['name'=>'Lourdes D. Dela Cruz-Umali','contact'=>'0916 830 2200','relation'=>'Mother'],'services'=>[]],
    ['id'=>'RES-2026-022','name'=>'Margarita L. Umali','sex'=>'Female','age'=>3,'dob'=>'2022-11-05','civil_status'=>'Single','barangay'=>'Baras','sitio'=>'Purok 1','household_id'=>'HH-2026-003','family_id'=>'FAM-2026-005','relation'=>'Daughter','contact'=>null,'occupation'=>null,'education'=>'Pre-School (Current)','income_range'=>'None','tags'=>['child','infant'],'verification'=>'Unverified','profile_pct'=>20,'status'=>'Active','created'=>'2025-05-15','last_updated'=>'2025-07-22','emergency'=>['name'=>'Lourdes D. Dela Cruz-Umali','contact'=>'0916 830 2200','relation'=>'Mother'],'services'=>[]],
    // HH-004 / FAM-006 Reyes Nuclear
    ['id'=>'RES-2026-023','name'=>'Andres B. Reyes','sex'=>'Male','age'=>45,'dob'=>'1980-12-01','civil_status'=>'Married','barangay'=>'Domorog','sitio'=>'Sitio Tibaon','household_id'=>'HH-2026-004','family_id'=>'FAM-2026-006','relation'=>'Head','contact'=>'0915 678 9901','occupation'=>'Fisherman','education'=>'Elementary Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>['high_risk'],'verification'=>'Partially Verified','profile_pct'=>68,'status'=>'Active','created'=>'2024-07-11','last_updated'=>'2026-04-18','emergency'=>['name'=>'Marilou G. Reyes','contact'=>'0915 678 9902','relation'=>'Spouse'],'services'=>[['date'=>'2025-11-04','type'=>'Certificate of Indigency','status'=>'Completed']]],
    ['id'=>'RES-2026-024','name'=>'Marilou G. Reyes','sex'=>'Female','age'=>42,'dob'=>'1983-05-17','civil_status'=>'Married','barangay'=>'Domorog','sitio'=>'Sitio Tibaon','household_id'=>'HH-2026-004','family_id'=>'FAM-2026-006','relation'=>'Spouse','contact'=>'0915 678 9902','occupation'=>'Housewife','education'=>'Elementary Graduate','income_range'=>'None','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>65,'status'=>'Active','created'=>'2024-07-11','last_updated'=>'2026-04-18','emergency'=>['name'=>'Andres B. Reyes','contact'=>'0915 678 9901','relation'=>'Spouse'],'services'=>[]],
    ['id'=>'RES-2026-025','name'=>'Nico B. Reyes','sex'=>'Male','age'=>19,'dob'=>'2006-09-14','civil_status'=>'Single','barangay'=>'Domorog','sitio'=>'Sitio Tibaon','household_id'=>'HH-2026-004','family_id'=>'FAM-2026-006','relation'=>'Son','contact'=>null,'occupation'=>'Unemployed','education'=>'Junior High School Graduate','income_range'=>'None','tags'=>['youth','osy'],'verification'=>'Unverified','profile_pct'=>35,'status'=>'Active','created'=>'2024-07-11','last_updated'=>'2025-01-08','emergency'=>['name'=>'Andres B. Reyes','contact'=>'0915 678 9901','relation'=>'Father'],'services'=>[]],
    ['id'=>'RES-2026-026','name'=>'Claudine B. Reyes','sex'=>'Female','age'=>16,'dob'=>'2009-03-28','civil_status'=>'Single','barangay'=>'Domorog','sitio'=>'Sitio Tibaon','household_id'=>'HH-2026-004','family_id'=>'FAM-2026-006','relation'=>'Daughter','contact'=>null,'occupation'=>'Student (Senior High)','education'=>'Senior High School (Current)','income_range'=>'None','tags'=>['youth','child'],'verification'=>'Unverified','profile_pct'=>30,'status'=>'Active','created'=>'2024-07-11','last_updated'=>'2024-12-05','emergency'=>['name'=>'Andres B. Reyes','contact'=>'0915 678 9901','relation'=>'Father'],'services'=>[]],
    // HH-005 / FAM-007 Flores Single Parent
    ['id'=>'RES-2026-027','name'=>'Grace E. Flores','sex'=>'Female','age'=>35,'dob'=>'1990-04-06','civil_status'=>'Separated','barangay'=>'Magsaysay','sitio'=>'Purok 3','household_id'=>'HH-2026-005','family_id'=>'FAM-2026-007','relation'=>'Head','contact'=>'0922 301 6605','occupation'=>'Laundrywoman','education'=>'High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>['solo_parent','4ps'],'verification'=>'Verified','profile_pct'=>84,'status'=>'Active','created'=>'2024-09-03','last_updated'=>'2026-06-28','emergency'=>['name'=>'Leticia Flores','contact'=>'0909 123 4567','relation'=>'Mother'],'services'=>[['date'=>'2026-04-20','type'=>'Solo Parent Cash Assistance','status'=>'Completed'],['date'=>'2026-01-14','type'=>'4Ps Monitoring Visit','status'=>'Completed']]],
    ['id'=>'RES-2026-028','name'=>'Miguel A. Flores','sex'=>'Male','age'=>13,'dob'=>'2012-11-18','civil_status'=>'Single','barangay'=>'Magsaysay','sitio'=>'Purok 3','household_id'=>'HH-2026-005','family_id'=>'FAM-2026-007','relation'=>'Son','contact'=>null,'occupation'=>'Student (Junior High)','education'=>'Junior High School (Current)','income_range'=>'None','tags'=>['youth','child','4ps'],'verification'=>'Unverified','profile_pct'=>40,'status'=>'Active','created'=>'2024-09-03','last_updated'=>'2025-08-12','emergency'=>['name'=>'Grace E. Flores','contact'=>'0922 301 6605','relation'=>'Mother'],'services'=>[]],
    ['id'=>'RES-2026-029','name'=>'Amara P. Flores','sex'=>'Female','age'=>10,'dob'=>'2015-07-25','civil_status'=>'Single','barangay'=>'Magsaysay','sitio'=>'Purok 3','household_id'=>'HH-2026-005','family_id'=>'FAM-2026-007','relation'=>'Daughter','contact'=>null,'occupation'=>'Student (Elementary)','education'=>'Elementary (Current)','income_range'=>'None','tags'=>['child','4ps'],'verification'=>'Unverified','profile_pct'=>35,'status'=>'Active','created'=>'2024-09-03','last_updated'=>'2025-06-20','emergency'=>['name'=>'Grace E. Flores','contact'=>'0922 301 6605','relation'=>'Mother'],'services'=>[]],
    // Edge-case / Data Quality records
    ['id'=>'RES-2026-030','name'=>'Dario M. Gonzales','sex'=>'Male','age'=>38,'dob'=>'1987-09-22','civil_status'=>'Married','barangay'=>'Agoho','sitio'=>'Purok 1','household_id'=>null,'family_id'=>null,'relation'=>null,'contact'=>'0933 220 8841','occupation'=>'Fisherman','education'=>'Elementary Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>45,'status'=>'Active','created'=>'2025-03-15','last_updated'=>'2025-09-01','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-031','name'=>'Felipa P. Santos','sex'=>'Female','age'=>68,'dob'=>'1957-04-10','civil_status'=>'Widow','barangay'=>'Masbaranon','sitio'=>'Sitio Malbog','household_id'=>null,'family_id'=>null,'relation'=>null,'contact'=>null,'occupation'=>'Retired','education'=>'Elementary Graduate','income_range'=>'Below ₱5,000/mo','tags'=>['senior'],'verification'=>'Unverified','profile_pct'=>22,'status'=>'Under Review','created'=>'2025-11-20','last_updated'=>'2026-01-14','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    // ── Citizen Portal sample residents (one per barangay) — kept in sync
    // with config/esperanza_citizens.php so each barangay's demo login
    // account is also a real, findable record here in the admin registry.
    ['id'=>'RES-2026-101','name'=>'Ronaldo Panganiban Bautista','sex'=>'Male','age'=>35,'dob'=>'1990-08-22','civil_status'=>'Married','barangay'=>'Labangtaytay','sitio'=>'Purok 2','household_id'=>'HH-2026-101','family_id'=>'FAM-2026-101','relation'=>'Head','contact'=>'0918 224 5567','occupation'=>'Fisherman','education'=>'Elementary Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>78,'status'=>'Active','created'=>'2015-01-01','last_updated'=>'2026-07-08','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-102','name'=>'Marites Gonzales Ferrer','sex'=>'Female','age'=>41,'dob'=>'1985-03-04','civil_status'=>'Married','barangay'=>'Agoho','sitio'=>'Purok 1','household_id'=>'HH-2026-102','family_id'=>'FAM-2026-102','relation'=>'Head','contact'=>'0917 335 8821','occupation'=>'Farmer','education'=>'High School Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>['farmer'],'verification'=>'Verified','profile_pct'=>82,'status'=>'Active','created'=>'2010-01-01','last_updated'=>'2026-07-02','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-103','name'=>'Joel Villanueva Aranas','sex'=>'Male','age'=>34,'dob'=>'1992-06-17','civil_status'=>'Single','barangay'=>'Almero','sitio'=>'Purok 3','household_id'=>'HH-2026-103','family_id'=>'FAM-2026-103','relation'=>'Head','contact'=>'0928 441 2093','occupation'=>'Tricycle Driver','education'=>'High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>65,'status'=>'Active','created'=>'2018-01-01','last_updated'=>'2026-06-20','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-104','name'=>'Cristy Pareja Bonghanoy','sex'=>'Female','age'=>37,'dob'=>'1988-11-29','civil_status'=>'Married','barangay'=>'Baras','sitio'=>'Purok 2','household_id'=>'HH-2026-104','family_id'=>'FAM-2026-104','relation'=>'Head','contact'=>'0919 502 7734','occupation'=>'Market Vendor','education'=>'High School Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>[],'verification'=>'Verified','profile_pct'=>90,'status'=>'Active','created'=>'2012-01-01','last_updated'=>'2026-07-15','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-105','name'=>'Ariel Santos Cabahug','sex'=>'Male','age'=>43,'dob'=>'1983-02-09','civil_status'=>'Married','barangay'=>'Domorog','sitio'=>'Purok 4','household_id'=>'HH-2026-105','family_id'=>'FAM-2026-105','relation'=>'Head','contact'=>'0906 213 4457','occupation'=>'Seafarer','education'=>'Vocational Graduate','income_range'=>'Middle (₱10,001–₱20,000/mo)','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>71,'status'=>'Active','created'=>'2008-01-01','last_updated'=>'2026-06-11','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-106','name'=>'Lorna Reyes Dimaano','sex'=>'Female','age'=>47,'dob'=>'1979-07-21','civil_status'=>'Widowed','barangay'=>'Guadalupe','sitio'=>'Purok 1','household_id'=>'HH-2026-106','family_id'=>'FAM-2026-106','relation'=>'Head','contact'=>'0917 809 1265','occupation'=>'Sari-Sari Store Owner','education'=>'High School Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>[],'verification'=>'Verified','profile_pct'=>88,'status'=>'Active','created'=>'2001-01-01','last_updated'=>'2026-07-20','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-107','name'=>'Bayani Cruz Espinosa','sex'=>'Male','age'=>31,'dob'=>'1995-04-30','civil_status'=>'Single','barangay'=>'Iligan','sitio'=>'Purok 2','household_id'=>'HH-2026-107','family_id'=>'FAM-2026-107','relation'=>'Head','contact'=>'0928 674 3312','occupation'=>'Farmer','education'=>'Junior High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>['farmer'],'verification'=>'Unverified','profile_pct'=>60,'status'=>'Active','created'=>'2019-01-01','last_updated'=>'2026-05-30','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-108','name'=>'Divina Torres Galvez','sex'=>'Female','age'=>39,'dob'=>'1986-10-12','civil_status'=>'Married','barangay'=>'Labrador','sitio'=>'Purok 3','household_id'=>'HH-2026-108','family_id'=>'FAM-2026-108','relation'=>'Head','contact'=>'0918 992 5501','occupation'=>'Public School Teacher','education'=>'College Graduate (BEEd)','income_range'=>'Middle (₱10,001–₱20,000/mo)','tags'=>[],'verification'=>'Verified','profile_pct'=>95,'status'=>'Active','created'=>'2011-01-01','last_updated'=>'2026-07-18','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-109','name'=>'Ferdinand Ramos Hilario','sex'=>'Male','age'=>46,'dob'=>'1980-01-25','civil_status'=>'Married','barangay'=>'Libertad','sitio'=>'Purok 1','household_id'=>'HH-2026-109','family_id'=>'FAM-2026-109','relation'=>'Head','contact'=>'0906 337 8890','occupation'=>'Carpenter','education'=>'High School Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>74,'status'=>'Active','created'=>'2005-01-01','last_updated'=>'2026-06-25','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-110','name'=>'Analiza Bautista Ibarra','sex'=>'Female','age'=>35,'dob'=>'1991-05-03','civil_status'=>'Married','barangay'=>'Magsaysay','sitio'=>'Purok 5','household_id'=>'HH-2026-110','family_id'=>'FAM-2026-110','relation'=>'Head','contact'=>'0917 664 2278','occupation'=>'OFW (on home leave)','education'=>'College Graduate (BSHM)','income_range'=>'Middle (₱10,001–₱20,000/mo)','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>68,'status'=>'Active','created'=>'2016-01-01','last_updated'=>'2026-07-01','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-111','name'=>'Romulo Flores Jacinto','sex'=>'Male','age'=>38,'dob'=>'1987-09-14','civil_status'=>'Married','barangay'=>'Masbaranon','sitio'=>'Purok 2','household_id'=>'HH-2026-111','family_id'=>'FAM-2026-111','relation'=>'Head','contact'=>'0928 118 6634','occupation'=>'Fisherman','education'=>'Elementary Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>[],'verification'=>'Verified','profile_pct'=>80,'status'=>'Active','created'=>'2013-01-01','last_updated'=>'2026-07-05','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-112','name'=>'Grace Mendoza Kalaw','sex'=>'Female','age'=>36,'dob'=>'1989-12-02','civil_status'=>'Single','barangay'=>'Poblacion','sitio'=>'Purok 6','household_id'=>'HH-2026-112','family_id'=>'FAM-2026-112','relation'=>'Head','contact'=>'0919 220 4471','occupation'=>'Municipal Utility Worker','education'=>'College Graduate (BSBA)','income_range'=>'Middle (₱10,001–₱20,000/mo)','tags'=>[],'verification'=>'Verified','profile_pct'=>92,'status'=>'Active','created'=>'2014-01-01','last_updated'=>'2026-07-22','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-113','name'=>'Danilo Aquino Lazaro','sex'=>'Male','age'=>42,'dob'=>'1984-08-08','civil_status'=>'Married','barangay'=>'Potingbato','sitio'=>'Purok 1','household_id'=>'HH-2026-113','family_id'=>'FAM-2026-113','relation'=>'Head','contact'=>'0906 550 7712','occupation'=>'Farmer','education'=>'Elementary Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>['farmer'],'verification'=>'Partially Verified','profile_pct'=>76,'status'=>'Active','created'=>'2009-01-01','last_updated'=>'2026-06-30','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-114','name'=>'Precious Domingo Manalo','sex'=>'Female','age'=>23,'dob'=>'2003-02-18','civil_status'=>'Single','barangay'=>'Rizal','sitio'=>'Purok 2','household_id'=>'HH-2026-114','family_id'=>'FAM-2026-114','relation'=>'Head','contact'=>'0917 903 5628','occupation'=>'College Student','education'=>'College Undergraduate','income_range'=>'None','tags'=>['youth'],'verification'=>'For Validation','profile_pct'=>55,'status'=>'Active','created'=>'2005-01-01','last_updated'=>'2026-05-15','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-115','name'=>'Ernesto Salazar Nierva','sex'=>'Male','age'=>45,'dob'=>'1981-06-06','civil_status'=>'Married','barangay'=>'San Roque','sitio'=>'Purok 3','household_id'=>'HH-2026-115','family_id'=>'FAM-2026-115','relation'=>'Head','contact'=>'0928 340 9915','occupation'=>'Tricycle Driver','education'=>'High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>70,'status'=>'Active','created'=>'2007-01-01','last_updated'=>'2026-06-08','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-116','name'=>'Josephine Castro Olivar','sex'=>'Female','age'=>36,'dob'=>'1990-03-27','civil_status'=>'Married','barangay'=>'Santiago','sitio'=>'Purok 1','household_id'=>'HH-2026-116','family_id'=>'FAM-2026-116','relation'=>'Head','contact'=>'0919 776 2240','occupation'=>'Seamstress','education'=>'High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>[],'verification'=>'Verified','profile_pct'=>84,'status'=>'Active','created'=>'2015-01-01','last_updated'=>'2026-07-12','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-117','name'=>'Ramil Garcia Pascua','sex'=>'Male','age'=>32,'dob'=>'1993-10-05','civil_status'=>'Single','barangay'=>'Sorosimbajan','sitio'=>'Purok 2','household_id'=>'HH-2026-117','family_id'=>'FAM-2026-117','relation'=>'Head','contact'=>'0906 481 6603','occupation'=>'Fisherman','education'=>'Junior High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>62,'status'=>'Active','created'=>'2020-01-01','last_updated'=>'2026-06-02','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-118','name'=>'Liezel Navarro Quimson','sex'=>'Female','age'=>32,'dob'=>'1994-07-19','civil_status'=>'Married','barangay'=>'Tawad','sitio'=>'Purok 1','household_id'=>'HH-2026-118','family_id'=>'FAM-2026-118','relation'=>'Head','contact'=>'0917 155 8867','occupation'=>'Sari-Sari Store Owner','education'=>'High School Graduate','income_range'=>'Below ₱5,000/mo','tags'=>[],'verification'=>'Partially Verified','profile_pct'=>73,'status'=>'Active','created'=>'2017-01-01','last_updated'=>'2026-06-27','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-119','name'=>'Dante Marquez Robles','sex'=>'Male','age'=>48,'dob'=>'1977-11-11','civil_status'=>'Married','barangay'=>'Tunga','sitio'=>'Purok 2','household_id'=>'HH-2026-119','family_id'=>'FAM-2026-119','relation'=>'Head','contact'=>'0928 226 4459','occupation'=>'Farmer','education'=>'Elementary Graduate','income_range'=>'Low (₱5,001–₱10,000/mo)','tags'=>['farmer'],'verification'=>'Verified','profile_pct'=>87,'status'=>'Active','created'=>'2003-01-01','last_updated'=>'2026-07-10','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
    ['id'=>'RES-2026-120','name'=>'Cherry Ann Villaflor Sarmiento','sex'=>'Female','age'=>30,'dob'=>'1996-04-04','civil_status'=>'Single','barangay'=>'Villa','sitio'=>'Purok 3','household_id'=>'HH-2026-120','family_id'=>'FAM-2026-120','relation'=>'Head','contact'=>'0919 447 3391','occupation'=>'Public School Teacher','education'=>'College Graduate (BSEd)','income_range'=>'Middle (₱10,001–₱20,000/mo)','tags'=>['youth'],'verification'=>'Partially Verified','profile_pct'=>66,'status'=>'Active','created'=>'2021-01-01','last_updated'=>'2026-06-18','emergency'=>['name'=>null,'contact'=>null,'relation'=>null],'services'=>[]],
];

// ── Barangay coverage (deterministic, sorted by pct desc) ─────────────────────
$barangayCoverage = collect([
    ['name'=>'Poblacion',    'residents'=>1842,'profiled'=>1842,'hh'=>482,'hh_profiled'=>482,'encoder'=>'Rowena Aguilar',     'last_visit'=>'2026-07-10','status'=>'Complete'],
    ['name'=>'Masbaranon',   'residents'=>1620,'profiled'=>1523,'hh'=>428,'hh_profiled'=>404,'encoder'=>'Bienvenido Salazar', 'last_visit'=>'2026-06-28','status'=>'In Progress'],
    ['name'=>'Baras',        'residents'=> 980,'profiled'=> 862,'hh'=>258,'hh_profiled'=>228,'encoder'=>'Dexter Villamor',    'last_visit'=>'2026-06-15','status'=>'In Progress'],
    ['name'=>'Iligan',       'residents'=> 860,'profiled'=> 754,'hh'=>226,'hh_profiled'=>199,'encoder'=>'Ferdinand Cortez',   'last_visit'=>'2026-05-20','status'=>'In Progress'],
    ['name'=>'Santiago',     'residents'=>1240,'profiled'=>1054,'hh'=>326,'hh_profiled'=>278,'encoder'=>'Dexter Villamor',    'last_visit'=>'2026-06-03','status'=>'In Progress'],
    ['name'=>'Magsaysay',    'residents'=> 940,'profiled'=> 769,'hh'=>246,'hh_profiled'=>202,'encoder'=>'Rowena Aguilar',     'last_visit'=>'2026-05-14','status'=>'In Progress'],
    ['name'=>'Domorog',      'residents'=> 760,'profiled'=> 610,'hh'=>200,'hh_profiled'=>162,'encoder'=>'Ferdinand Cortez',   'last_visit'=>'2026-04-22','status'=>'Needs Follow-up'],
    ['name'=>'San Roque',    'residents'=> 640,'profiled'=> 493,'hh'=>168,'hh_profiled'=>130,'encoder'=>'Angeline Mercado',   'last_visit'=>'2026-05-02','status'=>'In Progress'],
    ['name'=>'Rizal',        'residents'=> 820,'profiled'=> 623,'hh'=>216,'hh_profiled'=>166,'encoder'=>'Bienvenido Salazar', 'last_visit'=>'2026-04-10','status'=>'In Progress'],
    ['name'=>'Libertad',     'residents'=> 720,'profiled'=> 540,'hh'=>190,'hh_profiled'=>143,'encoder'=>'Angeline Mercado',   'last_visit'=>'2026-05-28','status'=>'In Progress'],
    ['name'=>'Guadalupe',    'residents'=> 860,'profiled'=> 637,'hh'=>226,'hh_profiled'=>168,'encoder'=>'Ferdinand Cortez',   'last_visit'=>'2026-04-05','status'=>'In Progress'],
    ['name'=>'Potingbato',   'residents'=> 680,'profiled'=> 496,'hh'=>178,'hh_profiled'=>131,'encoder'=>'Rowena Aguilar',     'last_visit'=>'2026-05-08','status'=>'In Progress'],
    ['name'=>'Villa',        'residents'=> 740,'profiled'=> 525,'hh'=>194,'hh_profiled'=>138,'encoder'=>'Dexter Villamor',    'last_visit'=>'2026-03-22','status'=>'Needs Follow-up'],
    ['name'=>'Agoho',        'residents'=>1080,'profiled'=> 756,'hh'=>284,'hh_profiled'=>200,'encoder'=>'Bienvenido Salazar', 'last_visit'=>'2026-04-18','status'=>'In Progress'],
    ['name'=>'Sorosimbajan', 'residents'=> 540,'profiled'=> 367,'hh'=>142,'hh_profiled'=> 97,'encoder'=>'Ferdinand Cortez',   'last_visit'=>'2026-03-10','status'=>'Needs Follow-up'],
    ['name'=>'Labrador',     'residents'=> 560,'profiled'=> 374,'hh'=>146,'hh_profiled'=> 98,'encoder'=>'Angeline Mercado',   'last_visit'=>'2026-03-05','status'=>'Needs Follow-up'],
    ['name'=>'Almero',       'residents'=> 480,'profiled'=> 302,'hh'=>126,'hh_profiled'=> 80,'encoder'=>'Rowena Aguilar',     'last_visit'=>'2026-02-14','status'=>'Needs Follow-up'],
    ['name'=>'Tunga',        'residents'=> 680,'profiled'=> 408,'hh'=>178,'hh_profiled'=>107,'encoder'=>'Dexter Villamor',    'last_visit'=>'2026-02-28','status'=>'Needs Follow-up'],
    ['name'=>'Labangtaytay', 'residents'=> 440,'profiled'=> 253,'hh'=>116,'hh_profiled'=> 68,'encoder'=>'Bienvenido Salazar', 'last_visit'=>'2026-01-22','status'=>'Needs Follow-up'],
    ['name'=>'Tawad',        'residents'=> 460,'profiled'=> 224,'hh'=>120,'hh_profiled'=> 63,'encoder'=>'Angeline Mercado',   'last_visit'=>'2025-12-08','status'=>'Not Started (Re-visit Required)'],
])->map(function ($b) {
    $b['pct']    = $b['residents'] > 0 ? (int) round($b['profiled'] / $b['residents'] * 100) : 0;
    $b['hh_pct'] = $b['hh']       > 0 ? (int) round($b['hh_profiled'] / $b['hh'] * 100)     : 0;
    return $b;
})->sortByDesc('pct')->values()->all();

// ── Data quality issues (12) ──────────────────────────────────────────────────
$dataQualityIssues = [
    ['id'=>'DQI-2026-001','type'=>'Orphaned Record',    'severity'=>'High',    'barangay'=>'Agoho',     'record_id'=>'RES-2026-030','record_name'=>'Dario M. Gonzales',          'description'=>'Resident has no linked household or family. Created 2025-03-15 — link was never completed during field encoding.','assigned_to'=>'Bienvenido Salazar','created'=>'2025-09-15','status'=>'Open',      'merge_candidate'=>null],
    ['id'=>'DQI-2026-002','type'=>'Duplicate Suspected','severity'=>'Critical','barangay'=>'Masbaranon','record_id'=>'RES-2026-031','record_name'=>'Felipa P. Santos',           'description'=>'May be a duplicate of a registered resident in the Santos household. Same surname, barangay, and approximate age.','assigned_to'=>'Rowena Aguilar',    'created'=>'2025-12-01','status'=>'In Review','merge_candidate'=>['record_id'=>'RES-2026-011','name'=>'Consuelo L. Santos','confidence'=>62]],
    ['id'=>'DQI-2026-003','type'=>'Incomplete Profile', 'severity'=>'Medium',  'barangay'=>'Domorog',   'record_id'=>'HH-2026-004', 'record_name'=>'Reyes Household',            'description'=>'Household profile below 60%. Missing: toilet facility, water source, flood evacuation plan. Zone 3 (High Risk) — completeness is critical.','assigned_to'=>'Ferdinand Cortez', 'created'=>'2026-02-10','status'=>'Open',      'merge_candidate'=>null],
    ['id'=>'DQI-2026-004','type'=>'Missing Documents',  'severity'=>'High',    'barangay'=>'Poblacion', 'record_id'=>'RES-2026-005','record_name'=>'Lucia A. Bacaltos',          'description'=>'For-validation status — PSA Birth Certificate and school ID not submitted despite multiple notices. Profile at 45%.','assigned_to'=>'Angeline Mercado',  'created'=>'2025-10-20','status'=>'Open',      'merge_candidate'=>null],
    ['id'=>'DQI-2026-005','type'=>'Missing Documents',  'severity'=>'Medium',  'barangay'=>'Poblacion', 'record_id'=>'RES-2026-009','record_name'=>'Rico T. Villanueva',         'description'=>'Unverified minor — no PSA Birth Certificate or PhilSys ID submitted. Family notified twice.','assigned_to'=>'Angeline Mercado',  'created'=>'2025-08-14','status'=>'Open',      'merge_candidate'=>null],
    ['id'=>'DQI-2026-006','type'=>'Stale Record',       'severity'=>'Medium',  'barangay'=>'Masbaranon','record_id'=>'RES-2026-014','record_name'=>'Roberto M. Aquino',          'description'=>'Boarder record not updated in over 12 months. No contact number verified. May have left the area.','assigned_to'=>'Bienvenido Salazar','created'=>'2026-04-05','status'=>'Open',      'merge_candidate'=>null],
    ['id'=>'DQI-2026-007','type'=>'Orphaned Record',    'severity'=>'High',    'barangay'=>'Masbaranon','record_id'=>'RES-2026-031','record_name'=>'Felipa P. Santos',           'description'=>'No household or family link present. Created during walk-in registration at barangay hall.','assigned_to'=>'Rowena Aguilar',    'created'=>'2025-11-20','status'=>'In Review','merge_candidate'=>null],
    ['id'=>'DQI-2026-008','type'=>'Incomplete Profile', 'severity'=>'Low',     'barangay'=>'Baras',     'record_id'=>'RES-2026-021','record_name'=>'Benjamin R. Dela Cruz',      'description'=>'Profile at 32% completion. Recently added — contact, income, and education fields not yet encoded.','assigned_to'=>'Dexter Villamor',   'created'=>'2025-05-10','status'=>'Open',      'merge_candidate'=>null],
    ['id'=>'DQI-2026-009','type'=>'Missing Documents',  'severity'=>'Medium',  'barangay'=>'Baras',     'record_id'=>'RES-2026-019','record_name'=>'Carlos A. Umali',            'description'=>'Partially verified — government-issued ID not on file. Listed as LGU employee but no ID submitted.','assigned_to'=>'Dexter Villamor',   'created'=>'2025-10-15','status'=>'Open',      'merge_candidate'=>null],
    ['id'=>'DQI-2026-010','type'=>'Incomplete Profile', 'severity'=>'Low',     'barangay'=>'Baras',     'record_id'=>'RES-2026-022','record_name'=>'Margarita L. Umali',         'description'=>'Infant record at 20% completion. PSA birth registration may not yet be processed.','assigned_to'=>'Dexter Villamor',   'created'=>'2025-07-25','status'=>'Open',      'merge_candidate'=>null],
    ['id'=>'DQI-2026-011','type'=>'Stale Record',       'severity'=>'Medium',  'barangay'=>'Domorog',   'record_id'=>'RES-2026-025','record_name'=>'Nico B. Reyes',              'description'=>'Not updated in 18 months. Tagged as OSY — may have migrated to another municipality.','assigned_to'=>'Ferdinand Cortez', 'created'=>'2026-01-12','status'=>'Open',      'merge_candidate'=>null],
    ['id'=>'DQI-2026-012','type'=>'Address Mismatch',   'severity'=>'Low',     'barangay'=>'Magsaysay', 'record_id'=>'HH-2026-005', 'record_name'=>'Flores Household',           'description'=>'System shows Purok 2 but 4Ps monitoring report lists Purok 3. Needs barangay captain confirmation.','assigned_to'=>'Rowena Aguilar',    'created'=>'2026-06-14','status'=>'Open',      'merge_candidate'=>null],
];

// ── Municipal summary (deterministic) ─────────────────────────────────────────
$municipalStats = [
    'residents'      => '17,842',
    'households'     => '4,918',
    'families'       => '6,204',
    'verified'       => '13,894',
    'pending'        => '1,856',
    'new_this_month' => '142',
    'issues'         => count($dataQualityIssues),
];

// ── Per-barangay headline stats (deterministic) ───────────────────────────────
$barangayStats = [
    'Poblacion'    => ['residents'=>'1,842','households'=>'482','families'=>'618','verified'=>'1,842','pending'=>'0',   'new_this_month'=>'18','issues'=>2],
    'Masbaranon'   => ['residents'=>'1,620','households'=>'428','families'=>'542','verified'=>'1,288','pending'=>'232','new_this_month'=>'12','issues'=>3],
    'Baras'        => ['residents'=>'980',  'households'=>'258','families'=>'326','verified'=>'796',  'pending'=>'148','new_this_month'=>'8', 'issues'=>4],
    'Iligan'       => ['residents'=>'860',  'households'=>'226','families'=>'284','verified'=>'690',  'pending'=>'120','new_this_month'=>'6', 'issues'=>1],
    'Santiago'     => ['residents'=>'1,240','households'=>'326','families'=>'412','verified'=>'980',  'pending'=>'188','new_this_month'=>'10','issues'=>2],
    'Magsaysay'    => ['residents'=>'940',  'households'=>'246','families'=>'308','verified'=>'722',  'pending'=>'152','new_this_month'=>'7', 'issues'=>1],
    'Domorog'      => ['residents'=>'760',  'households'=>'200','families'=>'252','verified'=>'566',  'pending'=>'142','new_this_month'=>'5', 'issues'=>2],
    'San Roque'    => ['residents'=>'640',  'households'=>'168','families'=>'210','verified'=>'466',  'pending'=>'112','new_this_month'=>'4', 'issues'=>0],
    'Rizal'        => ['residents'=>'820',  'households'=>'216','families'=>'272','verified'=>'582',  'pending'=>'148','new_this_month'=>'6', 'issues'=>1],
    'Libertad'     => ['residents'=>'720',  'households'=>'190','families'=>'238','verified'=>'498',  'pending'=>'138','new_this_month'=>'5', 'issues'=>0],
    'Guadalupe'    => ['residents'=>'860',  'households'=>'226','families'=>'284','verified'=>'584',  'pending'=>'168','new_this_month'=>'7', 'issues'=>1],
    'Potingbato'   => ['residents'=>'680',  'households'=>'178','families'=>'224','verified'=>'446',  'pending'=>'132','new_this_month'=>'5', 'issues'=>0],
    'Villa'        => ['residents'=>'740',  'households'=>'194','families'=>'244','verified'=>'470',  'pending'=>'150','new_this_month'=>'6', 'issues'=>1],
    'Agoho'        => ['residents'=>'1,080','households'=>'284','families'=>'354','verified'=>'702',  'pending'=>'228','new_this_month'=>'9', 'issues'=>1],
    'Sorosimbajan' => ['residents'=>'540',  'households'=>'142','families'=>'178','verified'=>'326',  'pending'=>'118','new_this_month'=>'4', 'issues'=>0],
    'Labrador'     => ['residents'=>'560',  'households'=>'146','families'=>'184','verified'=>'320',  'pending'=>'128','new_this_month'=>'4', 'issues'=>0],
    'Almero'       => ['residents'=>'480',  'households'=>'126','families'=>'158','verified'=>'264',  'pending'=>'120','new_this_month'=>'3', 'issues'=>0],
    'Tunga'        => ['residents'=>'680',  'households'=>'178','families'=>'224','verified'=>'350',  'pending'=>'196','new_this_month'=>'5', 'issues'=>0],
    'Labangtaytay' => ['residents'=>'440',  'households'=>'116','families'=>'146','verified'=>'220',  'pending'=>'128','new_this_month'=>'3', 'issues'=>0],
    'Tawad'        => ['residents'=>'460',  'households'=>'120','families'=>'150','verified'=>'208',  'pending'=>'160','new_this_month'=>'3', 'issues'=>0],
];

return compact('households','families','individuals','barangayCoverage','dataQualityIssues','municipalStats','barangayStats');
