<?php

// Static reference data for INTERNAL staff/office forms — these are
// LGU-personnel-facing (leave applications, property custodian slips, field
// monitoring reports, etc.), not citizen-facing, so they live in the
// Administrative Portal's "Internal Forms" module rather than Dokyu/Tulong.
// Same category/shape as config/esperanza_municipal_documents.php: shared
// display data consumed by a wizard + preview, just scoped to staff.
//
// Field data was extracted from the actual office forms provided
// (MHRMO/MGSO/Municipal Agriculture Office), trimmed to what an employee
// would fill in themselves — signature blocks, office-only certification
// sections, and system-generated numbers are left out since this is a
// frontend-only request/logging tool, not the source of truth registry.

return [
    'offices' => [
        'hr' => [
            'label' => 'Human Resource Management Office',
            'shortLabel' => 'MHRMO',
            'icon' => 'users-round',
            'forms' => [
                [
                    'key' => 'hr_application_for_leave',
                    'name' => 'Application for Leave',
                    'formNo' => 'Civil Service Form No. 6 (Revised 2020)',
                    'title' => 'APPLICATION FOR LEAVE',
                    'days' => '1-3 working days',
                    'requirements' => [
                        'Medical Certificate — required if Sick Leave is filed in advance or exceeds 5 days',
                        'Updated Solo Parent ID — required for Solo Parent Leave',
                        'Clearance from money, property, and work accountabilities — required for leave of 30+ calendar days or terminal leave',
                    ],
                    'process' => ['Submit Application', 'Certification of Leave Credits', 'Head of Office Recommendation', 'Approval'],
                    'fields' => [
                        ['key' => 'office_department', 'label' => 'Office / Department', 'type' => 'text', 'required' => true],
                        ['key' => 'position', 'label' => 'Position', 'type' => 'text'],
                        ['key' => 'salary', 'label' => 'Salary', 'type' => 'text'],
                        ['key' => 'leave_type', 'label' => 'Type of Leave to be Availed Of', 'type' => 'select', 'options' => [
                            'Vacation Leave', 'Mandatory/Forced Leave', 'Sick Leave', 'Maternity Leave', 'Paternity Leave',
                            'Special Privilege Leave', 'Solo Parent Leave', 'Study Leave', '10-Day VAWC Leave',
                            'Rehabilitation Privilege', 'Special Leave Benefits for Women', 'Special Emergency (Calamity) Leave', 'Adoption Leave',
                        ]],
                        ['key' => 'leave_details', 'label' => 'Details (location if Vacation/Special Privilege, illness if Sick, etc.)', 'type' => 'text'],
                        ['key' => 'number_of_days', 'label' => 'Number of Working Days Applied For', 'type' => 'number'],
                        ['key' => 'inclusive_dates', 'label' => 'Inclusive Dates', 'type' => 'text'],
                        ['key' => 'commutation', 'label' => 'Commutation', 'type' => 'select', 'options' => ['Not Requested', 'Requested']],
                    ],
                ],
                [
                    'key' => 'hr_personal_data_sheet',
                    'name' => 'Personal Data Sheet',
                    'formNo' => 'Civil Service Form No. 212 (Revised 2025)',
                    'title' => 'PERSONAL DATA SHEET',
                    'days' => 'N/A — for HR 201 file',
                    'requirements' => [
                        '1x1 or 2x2 ID photo',
                        'Photocopy of eligibility / rating (PRC, CSC, Board Exam, etc.)',
                    ],
                    'process' => ['Submit PDS', 'HR Verification', 'Encoding to 201 File'],
                    'fields' => [
                        ['key' => 'surname', 'label' => 'Surname', 'type' => 'text', 'required' => true],
                        ['key' => 'first_name', 'label' => 'First Name', 'type' => 'text', 'required' => true],
                        ['key' => 'middle_name', 'label' => 'Middle Name', 'type' => 'text'],
                        ['key' => 'date_of_birth', 'label' => 'Date of Birth', 'type' => 'date'],
                        ['key' => 'place_of_birth', 'label' => 'Place of Birth', 'type' => 'text'],
                        ['key' => 'sex', 'label' => 'Sex', 'type' => 'select', 'options' => ['Male', 'Female']],
                        ['key' => 'civil_status', 'label' => 'Civil Status', 'type' => 'select', 'options' => ['Single', 'Married', 'Widow/er', 'Separated', 'Solo Parent', 'Others']],
                        ['key' => 'citizenship', 'label' => 'Citizenship', 'type' => 'text', 'default' => 'Filipino'],
                        ['key' => 'height', 'label' => 'Height (m)', 'type' => 'text'],
                        ['key' => 'weight', 'label' => 'Weight (kg)', 'type' => 'text'],
                        ['key' => 'blood_type', 'label' => 'Blood Type', 'type' => 'select', 'options' => ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']],
                        ['key' => 'residential_address', 'label' => 'Residential Address', 'type' => 'text'],
                        ['key' => 'permanent_address', 'label' => 'Permanent Address', 'type' => 'text'],
                        ['key' => 'telephone_no', 'label' => 'Telephone No.', 'type' => 'text'],
                        ['key' => 'mobile_no', 'label' => 'Mobile No.', 'type' => 'text'],
                        ['key' => 'gsis_no', 'label' => 'GSIS ID No.', 'type' => 'text'],
                        ['key' => 'pagibig_no', 'label' => 'Pag-IBIG ID No.', 'type' => 'text'],
                        ['key' => 'philhealth_no', 'label' => 'PhilHealth No.', 'type' => 'text'],
                        ['key' => 'sss_no', 'label' => 'SSS No.', 'type' => 'text'],
                        ['key' => 'tin_no', 'label' => 'TIN No.', 'type' => 'text'],
                        ['key' => 'family_background', 'label' => 'Family Background', 'type' => 'table', 'rowIcon' => 'user-round', 'rowLabel' => 'Relative', 'columns' => [
                            ['key' => 'relation', 'label' => 'Relation'],
                            ['key' => 'name', 'label' => 'Full Name'],
                            ['key' => 'occupation', 'label' => 'Occupation'],
                        ]],
                        ['key' => 'educational_background', 'label' => 'Educational Background', 'type' => 'table', 'rowIcon' => 'graduation-cap', 'rowLabel' => 'School', 'columns' => [
                            ['key' => 'level', 'label' => 'Level'],
                            ['key' => 'school', 'label' => 'School Name'],
                            ['key' => 'degree', 'label' => 'Degree / Course'],
                            ['key' => 'from_to', 'label' => 'Period (From-To)'],
                            ['key' => 'year_graduated', 'label' => 'Year Graduated'],
                            ['key' => 'honors', 'label' => 'Honors Received'],
                        ]],
                        ['key' => 'civil_service_eligibility', 'label' => 'Civil Service Eligibility', 'type' => 'table', 'rowIcon' => 'award', 'rowLabel' => 'Eligibility', 'columns' => [
                            ['key' => 'eligibility', 'label' => 'Eligibility'],
                            ['key' => 'rating', 'label' => 'Rating'],
                            ['key' => 'date_of_exam', 'label' => 'Date of Exam'],
                            ['key' => 'place_of_exam', 'label' => 'Place of Exam'],
                        ]],
                        ['key' => 'work_experience', 'label' => 'Work Experience', 'type' => 'table', 'rowIcon' => 'briefcase', 'rowLabel' => 'Position', 'columns' => [
                            ['key' => 'from_to', 'label' => 'Period (From-To)'],
                            ['key' => 'position_title', 'label' => 'Position Title'],
                            ['key' => 'department_agency', 'label' => 'Department / Agency'],
                            ['key' => 'salary', 'label' => 'Monthly Salary'],
                            ['key' => 'status_of_appointment', 'label' => 'Status of Appointment'],
                        ]],
                        ['key' => 'voluntary_work', 'label' => 'Voluntary Work / Involvement', 'type' => 'table', 'rowIcon' => 'heart-handshake', 'rowLabel' => 'Engagement', 'columns' => [
                            ['key' => 'organization', 'label' => 'Organization'],
                            ['key' => 'from_to', 'label' => 'Period (From-To)'],
                            ['key' => 'hours', 'label' => 'No. of Hours'],
                            ['key' => 'position', 'label' => 'Position / Nature of Work'],
                        ]],
                        ['key' => 'training_programs', 'label' => 'Learning and Development (Trainings) Attended', 'type' => 'table', 'rowIcon' => 'graduation-cap', 'rowLabel' => 'Training', 'columns' => [
                            ['key' => 'title', 'label' => 'Title'],
                            ['key' => 'from_to', 'label' => 'Period (From-To)'],
                            ['key' => 'hours', 'label' => 'No. of Hours'],
                            ['key' => 'conducted_by', 'label' => 'Conducted / Sponsored By'],
                        ]],
                    ],
                ],
                [
                    'key' => 'hr_medical_certificate',
                    'name' => 'Medical Certificate',
                    'formNo' => 'Civil Service Form No. 211 (Revised 2025)',
                    'title' => 'MEDICAL CERTIFICATE',
                    'days' => '1 working day',
                    'requirements' => ['Valid government-issued ID', 'Laboratory results (Urinalysis, Chest X-Ray, Blood Test, Drug Test)'],
                    'process' => ['Submit Request', 'Medical Examination', 'Certificate Release'],
                    'fields' => [
                        ['key' => 'full_name', 'label' => 'Full Name', 'type' => 'text', 'required' => true],
                        ['key' => 'address', 'label' => 'Address', 'type' => 'text'],
                        ['key' => 'age', 'label' => 'Age', 'type' => 'number'],
                        ['key' => 'sex', 'label' => 'Sex', 'type' => 'select', 'options' => ['Male', 'Female']],
                        ['key' => 'civil_status', 'label' => 'Civil Status', 'type' => 'select', 'options' => ['Single', 'Married', 'Widowed', 'Separated']],
                        ['key' => 'agency_address', 'label' => 'Agency / Address', 'type' => 'text'],
                        ['key' => 'proposed_position', 'label' => 'Proposed Position', 'type' => 'text'],
                        ['key' => 'date_examined', 'label' => 'Date Examined', 'type' => 'date'],
                    ],
                ],
                [
                    'key' => 'hr_clearance',
                    'name' => 'Clearance Form',
                    'formNo' => 'Civil Service Form No. 7',
                    'title' => 'CLEARANCE',
                    'days' => '2-3 working days',
                    'requirements' => ['Approved Application for Leave or Resignation Letter, if applicable'],
                    'process' => ['Submit Request', 'Office-by-Office Clearance', 'Head of Office Certification', 'Release'],
                    'fields' => [
                        ['key' => 'full_name', 'label' => 'Full Name', 'type' => 'text', 'required' => true],
                        ['key' => 'office_to_clear', 'label' => 'Office/Section Clearing From', 'type' => 'text'],
                        ['key' => 'purpose', 'label' => 'Purpose of Clearance', 'type' => 'select', 'options' => ['Terminal Leave', 'Retirement', 'Resignation', 'Travel Abroad', 'Scholarship', 'Other']],
                        ['key' => 'pending_case', 'label' => 'Pending Administrative Case?', 'type' => 'select', 'options' => ['None', 'With Pending Case (Under Investigation)']],
                    ],
                ],
                [
                    'key' => 'hr_locator_slip',
                    'name' => 'Locator Slip',
                    'formNo' => 'MHRMO Locator Slip',
                    'title' => 'LOCATOR SLIP',
                    'days' => 'Same day',
                    'requirements' => ['Approval of Department Head / Unit Head'],
                    'process' => ['Submit Request', 'Department Head Approval', 'Release'],
                    'fields' => [
                        ['key' => 'full_name', 'label' => 'Name', 'type' => 'text', 'required' => true],
                        ['key' => 'position_designation', 'label' => 'Position/Designation', 'type' => 'text'],
                        ['key' => 'unit_department', 'label' => 'Unit/Department', 'type' => 'text'],
                        ['key' => 'purpose_of_travel', 'label' => 'Purpose of Travel', 'type' => 'text'],
                        ['key' => 'travel_type', 'label' => 'Type', 'type' => 'select', 'options' => ['Official Business', 'Official Time']],
                        ['key' => 'date_and_time', 'label' => 'Date and Time', 'type' => 'text'],
                        ['key' => 'destination', 'label' => 'Destination', 'type' => 'text'],
                    ],
                ],
                [
                    'key' => 'hr_pass_slip',
                    'name' => 'Pass Slip for Personal Business',
                    'formNo' => 'MHRMO Pass Slip',
                    'title' => 'PASS SLIP FOR PERSONAL BUSINESS',
                    'days' => 'Same day',
                    'requirements' => ['Approval of Head of Office / Authorized Representative'],
                    'process' => ['Submit Request', 'Head of Office Approval', 'Release'],
                    'fields' => [
                        ['key' => 'full_name', 'label' => 'Name', 'type' => 'text', 'required' => true],
                        ['key' => 'permission_type', 'label' => 'Permission Requested', 'type' => 'select', 'options' => ['Leave premises during office hours', 'Deviate from fixed time of arrival']],
                        ['key' => 'time_from', 'label' => 'Time From', 'type' => 'text'],
                        ['key' => 'time_to', 'label' => 'Time To', 'type' => 'text'],
                        ['key' => 'purpose', 'label' => 'Purpose (Optional)', 'type' => 'text'],
                    ],
                ],
            ],
        ],
        'gso' => [
            'label' => 'General Services Office',
            'shortLabel' => 'MGSO',
            'icon' => 'warehouse',
            'forms' => [
                [
                    'key' => 'gso_borrowers_slip',
                    'name' => "Borrower's Slip",
                    'formNo' => 'MGSO Borrower\'s Slip',
                    'title' => "BORROWER'S SLIP",
                    'days' => 'Same day',
                    'requirements' => ['Valid government-issued ID'],
                    'process' => ['Submit Request', 'MGSO Approval', 'Item Release'],
                    'fields' => [
                        ['key' => 'borrower_name', 'label' => "Borrower's Name", 'type' => 'text', 'required' => true],
                        ['key' => 'address', 'label' => 'Address', 'type' => 'text'],
                        ['key' => 'office_agency', 'label' => 'Office/Agency', 'type' => 'text'],
                        ['key' => 'contact_no', 'label' => 'Contact No.', 'type' => 'text'],
                        ['key' => 'date_of_return', 'label' => 'Expected Date of Return', 'type' => 'date'],
                        ['key' => 'items', 'label' => 'Property Information', 'type' => 'table', 'rowIcon' => 'package', 'rowLabel' => 'Item', 'columns' => [
                            ['key' => 'quantity', 'label' => 'Quantity'],
                            ['key' => 'unit', 'label' => 'Unit of Measure'],
                            ['key' => 'description', 'label' => 'Item Description'],
                            ['key' => 'remarks', 'label' => 'Remarks'],
                        ]],
                    ],
                ],
                [
                    'key' => 'gso_trip_ticket',
                    'name' => "Driver's Trip Ticket",
                    'formNo' => 'MGSO Trip Ticket (Blue)',
                    'title' => "DRIVER'S TRIP TICKET",
                    'days' => 'Same day',
                    'requirements' => ['Authorization from Administrative Official'],
                    'process' => ['Submit Request', 'MGSO Authorization', 'Vehicle Dispatch'],
                    'fields' => [
                        ['key' => 'trip_date', 'label' => 'Date', 'type' => 'date', 'required' => true],
                        ['key' => 'driver_name', 'label' => 'Name of Driver', 'type' => 'text'],
                        ['key' => 'vehicle_plate_no', 'label' => 'Government Vehicle Plate No.', 'type' => 'text'],
                        ['key' => 'passengers', 'label' => 'Name of Authorized Passenger/s', 'type' => 'text'],
                        ['key' => 'places_to_visit', 'label' => 'Place/s to be Visited', 'type' => 'text'],
                        ['key' => 'purpose', 'label' => 'Purpose', 'type' => 'text'],
                    ],
                ],
                [
                    'key' => 'gso_fuel_pass',
                    'name' => 'Fuel Pass',
                    'formNo' => 'LGU-Esperanza Fuel Pass',
                    'title' => 'FUEL PASS',
                    'days' => 'Same day',
                    'requirements' => ['Approved Driver\'s Trip Ticket'],
                    'process' => ['Submit Request', 'GSO Approval', 'Fuel Issuance'],
                    'fields' => [
                        ['key' => 'requesting_office', 'label' => 'Requesting Office', 'type' => 'text', 'required' => true],
                        ['key' => 'requestor_name', 'label' => "Requestor's Name", 'type' => 'text'],
                        ['key' => 'purpose', 'label' => 'Purpose', 'type' => 'text'],
                        ['key' => 'fuel_type', 'label' => 'Fuel Type', 'type' => 'select', 'options' => ['Diesel', 'Gasoline']],
                        ['key' => 'liters', 'label' => 'Liters Requested', 'type' => 'number'],
                    ],
                ],
                [
                    'key' => 'gso_inventory_custodian_slip',
                    'name' => 'Inventory Custodian Slip',
                    'formNo' => 'Annex A.3',
                    'title' => 'INVENTORY CUSTODIAN SLIP',
                    'days' => '1-2 working days',
                    'requirements' => ['Approved Purchase Request / Delivery Receipt, if applicable'],
                    'process' => ['Submit Request', 'Property Verification', 'Custodian Acknowledgment'],
                    'fields' => [
                        ['key' => 'entity_name', 'label' => 'Entity Name', 'type' => 'text', 'required' => true],
                        ['key' => 'fund_cluster', 'label' => 'Fund Cluster', 'type' => 'text'],
                        ['key' => 'received_from', 'label' => 'Received From', 'type' => 'text'],
                        ['key' => 'position_office', 'label' => 'Position/Office', 'type' => 'text'],
                        ['key' => 'items', 'label' => 'Item Information', 'type' => 'table', 'rowIcon' => 'package', 'rowLabel' => 'Item', 'columns' => [
                            ['key' => 'item_no', 'label' => 'Item No.'],
                            ['key' => 'description', 'label' => 'Description'],
                            ['key' => 'unit', 'label' => 'Unit'],
                            ['key' => 'quantity', 'label' => 'Qnty'],
                            ['key' => 'unit_cost', 'label' => 'Estimated Unit Cost'],
                            ['key' => 'total_cost', 'label' => 'Total Cost'],
                            ['key' => 'useful_life', 'label' => 'Useful Life'],
                        ]],
                    ],
                ],
                [
                    'key' => 'gso_return_slip',
                    'name' => 'Return Slip',
                    'formNo' => 'MGSO Return Slip',
                    'title' => 'RETURN SLIP',
                    'days' => 'Same day',
                    'requirements' => ['Original Borrower\'s Slip or Inventory Custodian Slip'],
                    'process' => ['Submit Return', 'Item Inspection', 'Acknowledgment'],
                    'fields' => [
                        ['key' => 'returned_by', 'label' => 'Returned By', 'type' => 'text', 'required' => true],
                        ['key' => 'office_address', 'label' => 'Office/Address', 'type' => 'text'],
                        ['key' => 'contact_no', 'label' => 'Contact No.', 'type' => 'text'],
                        ['key' => 'date_returned', 'label' => 'Date Returned', 'type' => 'date'],
                        ['key' => 'items', 'label' => 'Information on Returned Property', 'type' => 'table', 'rowIcon' => 'package', 'rowLabel' => 'Item', 'columns' => [
                            ['key' => 'quantity', 'label' => 'Quantity'],
                            ['key' => 'unit', 'label' => 'Unit of Measure'],
                            ['key' => 'description', 'label' => 'Item Description'],
                            ['key' => 'remarks', 'label' => 'Remarks'],
                        ]],
                    ],
                ],
                [
                    'key' => 'gso_waste_materials_report',
                    'name' => 'Waste Materials Report',
                    'formNo' => 'Appendix 65',
                    'title' => 'WASTE MATERIALS REPORT',
                    'days' => '3-5 working days',
                    'requirements' => ['Certificate of Inspection', 'Property/Supply Custodian endorsement'],
                    'process' => ['Submit Report', 'Inspection', 'Disposal Approval'],
                    'fields' => [
                        ['key' => 'entity_name', 'label' => 'Entity Name', 'type' => 'text', 'required' => true],
                        ['key' => 'fund_cluster', 'label' => 'Fund Cluster', 'type' => 'text'],
                        ['key' => 'place_of_storage', 'label' => 'Place of Storage', 'type' => 'text'],
                        ['key' => 'disposal_method', 'label' => 'Disposal Method', 'type' => 'select', 'options' => ['Destroyed', 'Sold at Private Sale', 'Sold at Public Auction', 'Transferred without Cost']],
                        ['key' => 'items', 'label' => 'Items for Disposal', 'type' => 'table', 'rowIcon' => 'package', 'rowLabel' => 'Item', 'columns' => [
                            ['key' => 'item', 'label' => 'Item'],
                            ['key' => 'quantity', 'label' => 'Quantity'],
                            ['key' => 'unit', 'label' => 'Unit'],
                            ['key' => 'description', 'label' => 'Description'],
                        ]],
                    ],
                ],
            ],
        ],
        'agriculture' => [
            'label' => 'Municipal Agriculture Office',
            'shortLabel' => 'Agriculture',
            'icon' => 'wheat',
            'forms' => [
                [
                    'key' => 'agri_animal_health_monitoring',
                    'name' => 'Animal Health Monitoring',
                    'formNo' => 'Animal Health Monitoring Log',
                    'title' => 'ANIMAL HEALTH MONITORING',
                    'days' => 'Same day (field log)',
                    'requirements' => [],
                    'process' => ['Field Visit', 'Log Entry', 'Submission to Livestock Coordinator'],
                    'fields' => [
                        ['key' => 'log_date', 'label' => 'Date', 'type' => 'date', 'required' => true],
                        ['key' => 'barangay', 'label' => 'Barangay', 'type' => 'text'],
                        ['key' => 'entries', 'label' => 'Monitoring Entries', 'type' => 'table', 'rowIcon' => 'paw-print', 'rowLabel' => 'Animal', 'columns' => [
                            ['key' => 'farmer_name', 'label' => 'Name of Farmer'],
                            ['key' => 'species', 'label' => 'Species'],
                            ['key' => 'sex', 'label' => 'Sex'],
                            ['key' => 'age', 'label' => 'Age'],
                            ['key' => 'antibiotic', 'label' => 'Anti-biotic'],
                            ['key' => 'vitamins', 'label' => 'Vitamins'],
                            ['key' => 'deworming', 'label' => 'Deworming'],
                            ['key' => 'remarks', 'label' => 'Remarks'],
                        ]],
                    ],
                ],
                [
                    'key' => 'agri_dog_vaccination_report',
                    'name' => 'Dog Vaccination Report',
                    'formNo' => 'DA Form V2017-01 (Bureau of Animal Industry)',
                    'title' => 'DOG VACCINATION REPORT',
                    'days' => 'Same day (field log)',
                    'requirements' => [],
                    'process' => ['Vaccination Drive', 'Log Entry', 'Submission to Bureau of Animal Industry'],
                    'fields' => [
                        ['key' => 'date_reported', 'label' => 'Date Reported', 'type' => 'date', 'required' => true],
                        ['key' => 'barangay', 'label' => 'Barangay', 'type' => 'text'],
                        ['key' => 'entries', 'label' => 'Client & Animal Information', 'type' => 'table', 'rowIcon' => 'dog', 'rowLabel' => 'Client', 'columns' => [
                            ['key' => 'first_name', 'label' => 'Owner First Name'],
                            ['key' => 'last_name', 'label' => 'Owner Last Name'],
                            ['key' => 'contact_no', 'label' => 'Contact No.'],
                            ['key' => 'animal_name', 'label' => 'Animal Name/Color/Breed'],
                            ['key' => 'species', 'label' => 'Species'],
                            ['key' => 'sex', 'label' => 'Sex'],
                            ['key' => 'age', 'label' => 'Age'],
                        ]],
                    ],
                ],
                [
                    'key' => 'agri_livestock_inventory',
                    'name' => 'Livestock and Poultry Inventory',
                    'formNo' => 'XII - Livestock and Poultry Inventory',
                    'title' => 'LIVESTOCK AND POULTRY INVENTORY',
                    'days' => 'N/A (annual survey)',
                    'requirements' => [],
                    'process' => ['Barangay Survey', 'Data Consolidation', 'Submission to Provincial Agriculture Office'],
                    'fields' => [
                        ['key' => 'barangay', 'label' => 'Barangay', 'type' => 'text', 'required' => true],
                        // Trimmed to the most common livestock/poultry categories for
                        // usability — the paper form's full column set (Carabao,
                        // Baka, Swine, Goat, Karnero, Chicken, Pabo, Gangsa, Ducks,
                        // Horse, Anay/Butakal, Boto, Piso, Mungaan, Sonoy, Pato,
                        // Itik, Rabbit) can be added as "Other" line items.
                        ['key' => 'entries', 'label' => 'Farmer Inventory', 'type' => 'table', 'rowIcon' => 'wheat', 'rowLabel' => 'Farmer', 'columns' => [
                            ['key' => 'farmer_name', 'label' => 'Name of Farmer'],
                            ['key' => 'carabao', 'label' => 'Carabao (M/F)'],
                            ['key' => 'cattle', 'label' => 'Cattle/Baka (M/F)'],
                            ['key' => 'swine', 'label' => 'Swine'],
                            ['key' => 'goat', 'label' => 'Goat (M/F)'],
                            ['key' => 'chicken', 'label' => 'Chicken'],
                            ['key' => 'duck', 'label' => 'Duck/Itik (M/F)'],
                            ['key' => 'other', 'label' => 'Other'],
                            ['key' => 'total', 'label' => 'Total'],
                        ]],
                    ],
                ],
                [
                    'key' => 'agri_annual_target',
                    'name' => 'Livestock and Poultry Annual Target',
                    'formNo' => 'Livestock & Poultry Annual Target',
                    'title' => 'LIVESTOCK AND POULTRY ANNUAL TARGET',
                    'days' => 'N/A (annual planning)',
                    'requirements' => [],
                    'process' => ['Draft Target', 'Municipal Agriculturist Review', 'Submission to Provincial Office'],
                    'fields' => [
                        ['key' => 'targets', 'label' => 'Targets by Program', 'type' => 'table', 'rowIcon' => 'target', 'rowLabel' => 'Program', 'columns' => [
                            ['key' => 'particular', 'label' => 'Particular'],
                            ['key' => 'program', 'label' => 'Program (HEMSEP / Rabies / Hog Cholera / Newcastle)'],
                            ['key' => 'annual_target', 'label' => 'Annual Target'],
                            ['key' => 'notes', 'label' => 'Notes'],
                        ]],
                    ],
                ],
                [
                    'key' => 'agri_accomplishment_report',
                    'name' => 'Accomplishment Report',
                    'formNo' => 'MAO Accomplishment Report',
                    'title' => 'ACCOMPLISHMENT REPORT',
                    'days' => 'N/A (periodic report)',
                    'requirements' => [],
                    'process' => ['Draft Report', 'Submit to Municipal Agriculturist', 'Noted & Filed'],
                    'fields' => [
                        ['key' => 'period_covered', 'label' => 'Period Covered', 'type' => 'text', 'required' => true],
                        ['key' => 'employee_name', 'label' => 'Name', 'type' => 'text'],
                        ['key' => 'designation', 'label' => 'Designation/Assignment', 'type' => 'text'],
                        ['key' => 'activities', 'label' => 'Activities', 'type' => 'table', 'rowIcon' => 'calendar-check', 'rowLabel' => 'Activity', 'columns' => [
                            ['key' => 'date', 'label' => 'Date'],
                            ['key' => 'activity', 'label' => 'Activities Undertaken/Conducted'],
                            ['key' => 'output', 'label' => 'Output/Accomplishment'],
                        ]],
                    ],
                ],
            ],
        ],
        'mswd' => [
            'label' => 'Social Welfare and Development Office',
            'shortLabel' => 'MSWD',
            'icon' => 'hand-heart',
            'forms' => [
                [
                    'key' => 'mswd_erpat_form',
                    'name' => 'ERPAT Association Activity Form',
                    'formNo' => 'ERPAT Federation of Esperanza, Masbate',
                    'title' => 'EMPOWERMENT AND RE-AFFIRMATION OF PATERNAL ABILITIES (ERPAT)',
                    'days' => '1-2 working days',
                    'requirements' => ['List of ERPAT Association Officers for the barangay'],
                    'process' => ['Submit Activity Form', 'MSWD Review', 'Filing'],
                    'fields' => [
                        ['key' => 'barangay', 'label' => 'Barangay', 'type' => 'text', 'required' => true],
                        ['key' => 'activity', 'label' => 'Activity', 'type' => 'text'],
                        ['key' => 'activity_date', 'label' => 'Date', 'type' => 'date'],
                        ['key' => 'venue', 'label' => 'Venue', 'type' => 'text'],
                        ['key' => 'president', 'label' => 'President', 'type' => 'text'],
                        ['key' => 'vice_president', 'label' => 'Vice President', 'type' => 'text'],
                        ['key' => 'secretary', 'label' => 'Secretary', 'type' => 'text'],
                        ['key' => 'treasurer', 'label' => 'Treasurer', 'type' => 'text'],
                        ['key' => 'attendees', 'label' => 'Attendees', 'type' => 'table', 'rowIcon' => 'user-round', 'rowLabel' => 'Attendee', 'columns' => [
                            ['key' => 'name', 'label' => 'Name'],
                            ['key' => 'occupation', 'label' => 'Occupation'],
                            ['key' => 'age', 'label' => 'Age'],
                        ]],
                    ],
                ],
            ],
        ],
    ],
];
